# Accuracy Analyzer Tool
The accuracy analyzer is used to debug accuracy issues with a given model on AIC with one specific input data.

The tool does the accuracy debugging by comparing raw tensor values w.r.t to some reference framework. The reference framework could be Onnx Runtime for onnx models, the AIC interpreter, Tensorflow and Caffe

## Requirements 
- Qualcomm Cloud AI 100 device
- Qualcomm AI 100 Software Development Kit >= 1.7
   - Platform SDK
   - Apps SDK 
- Python 3.8*-devel 
     - Centos: yum install python3-devel
     - Ubuntu: apt-get install python3-dev

### Setting up the Environment

#### Adding Kernel to Jupyter Notebook/Lab

In [1]:
!/opt/qti-aic/dev/python/qaic-env/bin/python -m pip install ipykernel 
!source /opt/qti-aic/dev/python/qaic-env/bin/activate &&  /opt/qti-aic/dev/python/qaic-env/bin/python -m ipykernel install --user --name qaic-env --display-name "Python (qaic-env)";

WARNING: The directory '/local/mnt/workspace/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Requirement already satisfied: ipykernel in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (6.25.0)
Requirement already satisfied: comm>=0.1.1 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (0.1.3)
Requirement already satisfied: debugpy>=1.6.5 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (8.12.2)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (8.3.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (5.3.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (0.1.6)
Requirement already satisfied: nest-asyncio in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (1.5.7)
Requirement already satisfied: packaging in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (23.1)
Requirement already satisfied: psutil in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (5.9.5)
Requirement already satisfied: pyzmq>=20 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (25.1.0)
Requirement already satisfied: tornado>=6.1 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (6.3.2)
Requirement already satisfied: traitlets>=5.4.0 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipykernel) (5.9.0)
Requirement already satisfied: backcall in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (0.2.0)
Requirement already satisfied: decorator in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (0.19.0)
Requirement already satisfied: pickleshare in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (2.15.1)
Requirement already satisfied: stack-data in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (0.6.2)
Requirement already satisfied: typing-extensions in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (4.7.1)
Requirement already satisfied: pexpect>4.3 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from ipython>=7.23.1->ipykernel) (4.8.0)
Requirement already satisfied: importlib-metadata>=4.8.3 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel) (6.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (3.10.0)
Requirement already satisfied: zipp>=0.5 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=6.1.12->ipykernel) (3.16.2)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: wcwidth in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel) (0.2.6)
Requirement already satisfied: six>=1.5 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: pure-eval in /opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.2)
Badly placed ()'s.



## Tool usage and options


usage: qaic-acc-analyzer.py [-h] 
           -model MODEL -input-list INPUT_LIST 
           [-reference {interpreter,onnxrt,tensorflow,caffe,none}] 
           [-input-info INPUT_INFO [INPUT_INFO ...]]
           [-snooping {layerwise,oneshot,fp16sweep}]
           [-start-from-layer-output START_FROM_LAYER_OUTPUT]
           [-end-layer-output END_LAYER_OUTPUT] 
           [-skip-layers SKIP_LAYERS] 
           [-skip-layer-outputs SKIP_LAYER_OUTPUTS] 
           [-add-layers ADD_LAYERS]
           [-add-layer-outputs ADD_LAYER_OUTPUTS]
           [-top-partition]
           [-skip-layer-patterns SKIP_LAYER_PATTERNS]
           [-aic-mode {sim,hw}]
           [-precision {int8,fp16,default}] 
           [-aic-compile-args AIC_COMPILE_ARGS]
           [-aic-exec-args AIC_EXEC_ARGS]
           [-device-id DEVICE_ID] 
           [-comparator COMPARATOR] 
           [-tol-thresh TOL_THRESH] 
           [-layer-tol-thresh LAYER_TOL_THRESH]
           [-layer-output-comparator LAYER_OUTPUT_COMPARATOR [LAYER_OUTPUT_COMPARATOR ...]] 
           [-enable-minimodels] 
           [-dump-debug-graph] 
           [-onnx-symbol ONNX_SYMBOL [ONNX_SYMBOL ...]]
           [-onnx-custom-op-lib ONNX_CUSTOM_OP_LIB] 
           [-onnxrt-quant-params ONNXRT_QUANT_PARAMS] 
           [-work-dir WORK_DIR] 
           [-skip-initial-run] 
           [-skip-ref-run] 
           [-save-partitions]
           [-fp16sweep-layers FP16SWEEP_LAYERS] 
           [-enable-compiler-snooping] 
           [-silent] 
           [-disable-graph-optimization] 
           [-extract] 
           [-disable-check-model] 
           [-disable-fusion-patterns]
           [-strategy {binary,sequential,pgq-sweep,none}] 
           [-num-sensitive-nodes NUM_SENSITIVE_NODES] 
           [-granularity GRANULARITY] 
           [-pgq-options PGQ_OPTIONS]


qaic-acc-analyzer Options

required options:
  -model MODEL          path to model (onnx)
  -input-list INPUT_LIST
                        list of model inputs in a txt file with each line containing comma delimited input raw files.
  -reference {interpreter,onnxrt,tensorflow,caffe,none}
                        select reference platform for comparison.

model options:
  -input-info INPUT_INFO [INPUT_INFO ...]
                        tuple of shape and dtype of inputs.e.g inp01,float,[1,3,416,416] .Can be called multiple times

Snooping options:
  -snooping {layerwise,oneshot,fp16sweep}
                        select snooping type. default: layerwise
  -start-from-layer-output START_FROM_LAYER_OUTPUT
                        start debugging from layer following this output node. default starts from first layer
  -end-layer-output END_LAYER_OUTPUT
                        end debugging at layer following this output node.
  -skip-layers SKIP_LAYERS
                        comma delimited layer types to skip snooping. e.g :Resize,Transpose
  -skip-layer-outputs SKIP_LAYER_OUTPUTS
                        comma delimited layer output names to skip snooping. e.g :1171, 1174
  -add-layers ADD_LAYERS
                        comma delimited layer types to snoop. e.g :Resize,Transpose. All enabled by default.
  -add-layer-outputs ADD_LAYER_OUTPUTS
                        Comma delimited layer output names to snoop e.g :1171,1174. All enabled by default.
  -top-partition        enable top partition to skip running complete model each time.
  -skip-layer-patterns SKIP_LAYER_PATTERNS
                        path to yaml file specifying layer patterns to be skipped. e.g [['Conv','Relu'],['Conv','Batchnorm','Relu']]

aic compiler options:
  -aic-mode {sim,hw}    select compiler mode(sim,hw). Default is hw
  -precision {int8,fp16,default}
                        select precision
  -aic-compile-args AIC_COMPILE_ARGS
                        additional compiler arguments in a quoted string
  -aic-exec-args AIC_EXEC_ARGS
                        additional execution arguments in a quoted string.
  -device-id DEVICE_ID  select particular device for compilation and execution

compare options:
  -comparator COMPARATOR
                        comma delimited comparators to be used. e.g avg,rme
  -tol-thresh TOL_THRESH
                        comma delimited tolerance thresholds for comparators.For abs comparator, this signifies the percentage difference allowed.For other comparators, its decides the decimal place to round. 0.001 means
                        round after 3rd decimal before compare. e.g 0.01,0.001
  -layer-tol-thresh LAYER_TOL_THRESH
                        layerwise tol thresholds which overrides the global thresholds. e.g Sigmoid:1e-5,BatchNorm:1e-1
  -layer-output-comparator LAYER_OUTPUT_COMPARATOR [LAYER_OUTPUT_COMPARATOR ...]
                        Layer specific comparator(s) e.g 1150:abd,rme. This option can be used multiple times for each o/p node

other options:
  -enable-minimodels    enable minimodel generation
  -dump-debug-graph     generate debug graph in svg format
  -onnx-symbol ONNX_SYMBOL [ONNX_SYMBOL ...]
                        Replace onnx symbols in input/output shapes.Can be passed multiple times.Default replaced by 1. e.g __unk_200:1
  -onnx-custom-op-lib ONNX_CUSTOM_OP_LIB
                        path to onnx custom operator library
  -onnxrt-quant-params ONNXRT_QUANT_PARAMS
                        Onnxrt quant params need to be passedwith semi colon delimiter seperating different params.ex: "per_chanel=True;reduce_range=True"
  -work-dir WORK_DIR    Working directory for debugger. Default : qdbg_temp
  -skip-initial-run     Skip initial run to get final outputs mismatch report
  -skip-ref-run         Skip run to save intermediate outputs on reference platform
  -save-partitions      saves all the intermediate model partitions
  -fp16sweep-layers FP16SWEEP_LAYERS
                        Perform Fp16 sweep only on these layer types
  -enable-compiler-snooping
                        Uses compiler to add intermediate outputs to model for snooping
  -silent               Disables user authorization to proceed oneshot snooping process
  -disable-graph-optimization
                        Disables basic graph optimizations like const-folding, etc..
  -extract              Extracts the subgraph for model at specified start and end layers
  -disable-check-model  Disables model validation check
  -disable-fusion-patterns
                        Disables pattern matcher which fetches all fusion patterns in model

strategy options:
  -strategy {binary,sequential,pgq-sweep,none}
                        select strategy type. default: "none"
  -num-sensitive-nodes NUM_SENSITIVE_NODES
                        No of sensitive nodes to be identified. To be used only with binary strategy option.For choices greater than 5, consider using layerwise snooping
  -granularity GRANULARITY
                        percentage of the sensitive sub-graph to be identified. To be used only with sequential strategy option.Value should be between 0 and 100.
  -pgq-options PGQ_OPTIONS
                        PGQ combinations that needs to be used with pgq-sweep strategy. Default behaviour is to run allthe possible combinations. Arguments should be given in a quoted string.e.g: quantization-
                        schema:asymmetric,symmetric_with_uint8;quantization-calibration:Percentile;channelwise:True;percentile-calibration-value:99.99

### Comparators

This option enables user to choose what kind of comparison to use to evaluate layerwise similarity between AIC and reference outputs. One can pass multiple comparators with this option

If the match is not 100%, its marked as a mismatched layer and the model shall be partitioned at that layer when using layerwise snooping.

Valid options:

 abs | rme | avg | l1norm | l2norm | cos | kld | std 

**Description of each comparator and its formulae:**

*Note:* Here op1 and op1 are the numpy output tensors from aic and reference platform 

**abs:**  
evaluates the absolute percent mismatch between two tensors (elementwise). Uses a tolerance threshold to control the allowed % deviation.
```
match = np.allclose(op1, op2, rtol=self._tol, equal_nan=True)
tdiff = np.isclose(op1, op2, rtol=self._tol, equal_nan=True)
common = op1[tdiff]
match_percent = (common.shape[0] * 100) / op2.shape[0]
```

**rme:**
Evaluates the RMSE between the two tensors.
```
rmse = np.linalg.norm(op2 - op1) / np.sqrt(len(op1))
match_percent = 100 - rmse
 ```       

**avg:**
Evaluates the error between the two tensors by dividing the absolute gap by average value of the tensors.
```
avg_value = np.nan_to_num(max(np.average(np.absolute(op1)), np.average(np.absolute(op2))))
if (avg_value != 0):
    avg_error = np.average(abs(op1 - op2)) / avg_value
else:
    avg_error = 0.0
avg_error *= 100.0
match_percent = 100 - avg_error
```

**l1norm, l2norm:**
Evaluates the L1 and L2 norm of the two tensors.
```
ord = 1 for l1norm
ord = 2 for l2nor  
diff = np.linalg.norm(op2 - op1, ord=1)
ref_norm = np.linalg.norm(op1, ord=1)
match_percent = 100 - (diff * 100 / ref_norm)
```

**cos:**
Evaluates the cosine similarity between the two tensors
```
cos_sim = np.dot(op1, op2)/ (np.linalg.norm(op1) * np.linalg.norm(op2))
match_percent = (1+cos_sim)/2 * 100
```

**kld:**
Evaluates the KL Divergence between the two tensors
```
kld = entropy(op1, op2, base=2)
```

**std:**
Evaluates the Relative Standard deviation between the two tensors Comparator is enabled by default and the tool supports various set of in built comparators.By default, average comparator is used.
```
std1 = np.std(op1)
std2 = np.std(op2)
pct_change = (abs(std2 - std1) / std1)*100
```

In [16]:
# Get the defaults from SDK into current work directory if doesnt exist.
import os
import shutil
import pandas as pd
import sys
if not os.path.exists('defaults.yaml'):
    !cp /opt/qti-aic/tools/qaic-pytools/defaults.yaml .
    

cwd = os.getcwd()
# delete old log directories
if os.path.exists(os.path.join(cwd , 'log_dir')):
    shutil.rmtree(os.path.join(cwd , 'log_dir'))
    
device_id = '0'
model_path = 'Resnet50/resnet50_v1.onnx'
list_file = 'Resnet50/list.txt'
input_file = 'Resnet50/dog.raw'
os.system('echo \"dog.raw\" > Resnet50/list.txt')

pgq_log = os.path.join(cwd ,'log_dir/pgq_log_dir')

# PGQ Sweep
This strategy is useful to identify the best possible PGQ combination. In this strategy, we do Oneshot snooping over all the possible PGQ combinations and identify the best possible combination. This is a good starting point to use the accuracy analyzer. After identifying the best possible combination user can try our various other strategies and snooping methods to identifying the sensitive nodes/sub-graphs. User can reduce the combinations to search by giving custom combinations with pgq-options parameter.

**Note:** This step is not required if user has results of Accuracy Evaluator

## Executing pgq sweep:

In [17]:
!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
        -model {model_path} \
        -input-list {list_file} \
        -work-dir {pgq_log} \
        -reference onnxrt \
        -precision int8 \
        -strategy pgq-sweep

/opt/qti-aic/dev/python/qaic-env/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
INFO: QAIC Model Analyzer
INFO: Cleaned and Optimized model is saved at /local/mnt/workspace/github/resnet/Analyzer/log_dir/pgq_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 125
INFO: Node types and count in the cleaned graph:
   op_type  count
      Conv     53
      Relu     49
       Add     17
   MaxPool      1
ReduceMean      1
   Squeeze      1
    MatMul      1
   Softmax      1
    ArgMax      1
INFO: Snooping all intermediate outputs of model
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Compiling and executing original model...
                  Layer Type      Shape Data Type Ref Activations (min,max,median) Aic Activations (Min,Max,Median)    Avg(%) Info
O/P Name
ArgMax_0           (*)ArgMax       (1,)     int64              (447, 447, 447.0)                (447, 447, 447.0)    100.0000    -
softmax_tensor_0  (*)Softmax  (1, 1001)   float32              (0.0, 0.034, 0.0)                (0.0, 0.022, 0.0)     61.5972    -
Results saved at /local/mnt/workspace/github/resnet/Analyzer/log_dir/pgq_log_dir/oneshot.csv
INFO: Final outputs mismatch observed.
INFO: Running pgq-sweep strategy on the model...
INFO: ===========================================================================] 100.0% (PGQ combinations: 54/54)
      quant-schema-activations quant-schema-constants       quant-calib channelwise % calibration  mean match%                                                                Orig Outputs
Index
1                   asymmetric              symmetric              None        True             -     78.44140    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.8828}}
2                   asymmetric              symmetric              None       False             -     78.29995    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.5999}}
3                   asymmetric              symmetric    KLMinimization        True             -     85.35740    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 70.7148}}
4                   asymmetric              symmetric    KLMinimization       False             -     88.94360    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 77.8872}}
5                   asymmetric              symmetric        Percentile        True          99.9     74.79575    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 49.5915}}
6                   asymmetric              symmetric        Percentile        True         99.99     78.49650     {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.993}}
7                   asymmetric              symmetric        Percentile        True        99.999     77.23835    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 54.4767}}
8                   asymmetric              symmetric        Percentile        True       99.9999     78.42395    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.8479}}
9                   asymmetric              symmetric        Percentile       False          99.9     78.03080    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.0616}}
10                  asymmetric              symmetric        Percentile       False         99.99     81.50270    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 63.0054}}
11                  asymmetric              symmetric        Percentile       False        99.999     81.84020    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 63.6804}}
12                  asymmetric              symmetric        Percentile       False       99.9999     79.69225    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 59.3845}}
13                  asymmetric              symmetric              SQNR        True             -     79.46520    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 58.9304}}
14                  asymmetric              symmetric              SQNR       False             -     79.00960    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 58.0192}}
15                  asymmetric              symmetric               MSE        True             -     83.99990    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 67.9998}}
16                  asymmetric              symmetric               MSE       False             -     85.12040    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 70.2408}}
17                  asymmetric              symmetric  KLMinimizationV2        True             -     44.07585  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 63.0958}}
18                  asymmetric              symmetric  KLMinimizationV2       False             -     48.57100  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 72.0861}}
19                  asymmetric             asymmetric              None        True             -     54.65100  {'ArgMax_0': {'Avg(%)': 63.6752}, 'softmax_tensor_0': {'Avg(%)': 45.6268}}
20                  asymmetric             asymmetric              None       False             -     82.25880    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 64.5176}}
21                  asymmetric             asymmetric    KLMinimization        True             -     85.58645    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 71.1729}}
22                  asymmetric             asymmetric    KLMinimization       False             -     82.20090    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 64.4018}}
23                  asymmetric             asymmetric        Percentile        True          99.9     76.21620    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 52.4324}}
24                  asymmetric             asymmetric        Percentile        True         99.99     78.82365    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 57.6473}}
25                  asymmetric             asymmetric        Percentile        True        99.999     78.32790    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.6558}}
26                  asymmetric             asymmetric        Percentile        True       99.9999     77.92935    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 55.8587}}
27                  asymmetric             asymmetric        Percentile       False          99.9     75.79700     {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 51.594}}
28                  asymmetric             asymmetric        Percentile       False         99.99     79.54720    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 59.0944}}
29                  asymmetric             asymmetric        Percentile       False        99.999     78.16015    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.3203}}
30                  asymmetric             asymmetric        Percentile       False       99.9999     79.45950     {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 58.919}}
31                  asymmetric             asymmetric              SQNR        True             -     77.07435    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 54.1487}}
32                  asymmetric             asymmetric              SQNR       False             -     81.82120    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 63.6424}}
33                  asymmetric             asymmetric               MSE        True             -     77.58830    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 55.1766}}
34                  asymmetric             asymmetric               MSE       False             -     81.33810    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 62.6762}}
35                  asymmetric             asymmetric  KLMinimizationV2        True             -     81.28605    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 62.5721}}
36                  asymmetric             asymmetric  KLMinimizationV2       False             -     74.37710     {'ArgMax_0': {'Avg(%)': 89.4}, 'softmax_tensor_0': {'Avg(%)': 59.3542}}
37        symmetric_with_uint8   symmetric_with_uint8              None        True             -     78.54750     {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 57.095}}
38        symmetric_with_uint8   symmetric_with_uint8              None       False             -     80.79860    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 61.5972}}
39        symmetric_with_uint8   symmetric_with_uint8    KLMinimization        True             -     46.02950  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 67.0031}}
40        symmetric_with_uint8   symmetric_with_uint8    KLMinimization       False             -     47.17990  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 69.3039}}
41        symmetric_with_uint8   symmetric_with_uint8        Percentile        True          99.9     76.67130    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 53.3426}}
42        symmetric_with_uint8   symmetric_with_uint8        Percentile        True         99.99     77.61660    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 55.2332}}
43        symmetric_with_uint8   symmetric_with_uint8        Percentile        True        99.999     77.50825    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 55.0165}}
44        symmetric_with_uint8   symmetric_with_uint8        Percentile        True       99.9999     76.56470    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 53.1294}}
45        symmetric_with_uint8   symmetric_with_uint8        Percentile       False          99.9     80.44095    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 60.8819}}
46        symmetric_with_uint8   symmetric_with_uint8        Percentile       False         99.99     81.72365    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 63.4473}}
47        symmetric_with_uint8   symmetric_with_uint8        Percentile       False        99.999     79.75650     {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 59.513}}
48        symmetric_with_uint8   symmetric_with_uint8        Percentile       False       99.9999     80.39065    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 60.7813}}
49        symmetric_with_uint8   symmetric_with_uint8              SQNR        True             -     78.30625    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 56.6125}}
50        symmetric_with_uint8   symmetric_with_uint8              SQNR       False             -     81.17105    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 62.3421}}
51        symmetric_with_uint8   symmetric_with_uint8               MSE        True             -     79.73025    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 59.4605}}
52        symmetric_with_uint8   symmetric_with_uint8               MSE       False             -     82.51285    {'ArgMax_0': {'Avg(%)': 100.0}, 'softmax_tensor_0': {'Avg(%)': 65.0257}}
53        symmetric_with_uint8   symmetric_with_uint8  KLMinimizationV2        True             -     45.56740  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 66.0789}}
54        symmetric_with_uint8   symmetric_with_uint8  KLMinimizationV2       False             -     47.89180  {'ArgMax_0': {'Avg(%)': 25.0559}, 'softmax_tensor_0': {'Avg(%)': 70.7277}}
Results saved at /local/mnt/workspace/github/resnet/Analyzer/log_dir/pgq_log_dir/pqg_sweep.csv
INFO: Best PGQ profile : quantization-schema-activations:asymmetric, quantization-schema-constants:symmetric, quantization-calibration: KLMinimization, channelwise: False, percentile-calibration-value: None
INFO: qaic-acc-analyzer ended successfully

### PGQ sweep result:
Best PGQ profile : quantization-schema:symmetric_with_uint8, quantization-calibration: None, channelwise: True, percentile-calibration-value: None

In [65]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
csv_path = os.path.join(cwd ,'log_dir/pgq_log_dir/pgq_sweep.csv')
df=pd.read_csv(csv_path)
df
# extra_options = '-aic-compile-args="quantization-schema=symmetric_with_uint8;enable-channelwise"'

,Index,quant-schema,quant-calib,channelwise,% calibration,mean match%,Orig Outputs
0,1,asymmetric,None,True,-,85.2417,"{'473': OrderedDict([('Avg(%)', 85.2417)])}"
1,2,asymmetric,None,False,-,79.5983,"{'473': OrderedDict([('Avg(%)', 79.5983)])}"
2,3,asymmetric,KLMinimization,True,-,83.7010,"{'473': OrderedDict([('Avg(%)', 83.701)])}"
3,4,asymmetric,KLMinimization,False,-,78.3025,"{'473': OrderedDict([('Avg(%)', 78.3025)])}"
4,5,asymmetric,Percentile,True,99.9,75.6176,"{'473': OrderedDict([('Avg(%)', 75.6176)])}"
5,6,asymmetric,Percentile,True,99.99,85.4364,"{'473': OrderedDict([('Avg(%)', 85.4364)])}"
6,7,asymmetric,Percentile,True,99.999,85.5984,"{'473': OrderedDict([('Avg(%)', 85.5984)])}"
7,8,asymmetric,Percentile,True,99.9999,85.6586,"{'473': OrderedDict([('Avg(%)', 85.6586)])}"
8,9,asymmetric,Percentile,False,99.9,72.7009,"{'473': OrderedDict([('Avg(%)', 72.7009)])}"
9,10,asymmetric,Percentile,False,99.99,79.1987,"{'473': OrderedDict([('Avg(%)', 79.1987)])}"
10,11,asymmetric,Percentile,False,99.999,79.1531,"{'473': OrderedDict([('Avg(%)', 79.1531)])}"
11,12,asymmetric,Percentile,False,99.9999,79.6161,"{'473': OrderedDict([('Avg(%)', 79.6161)])}"
12,13,symmetric_with_uint8,None,True,-,88.0499,"{'473': OrderedDict([('Avg(%)', 88.0499)])}"
13,14,symmetric_with_uint8,None,False,-,69.3158,"{'473': OrderedDict([('Avg(%)', 69.3158)])}"
14,15,symmetric_with_uint8,KLMinimization,True,-,86.9022,"{'473': OrderedDict([('Avg(%)', 86.9022)])}"
15,16,symmetric_with_uint8,KLMinimization,False,-,68.4347,"{'473': OrderedDict([('Avg(%)', 68.4347)])}"
16,17,symmetric_with_uint8,Percentile,True,99.9,76.0523,"{'473': OrderedDict([('Avg(%)', 76.0523)])}"
17,18,symmetric_with_uint8,Percentile,True,99.99,85.5560,"{'473': OrderedDict([('Avg(%)', 85.556)])}"
18,19,symmetric_with_uint8,Percentile,True,99.999,87.8716,"{'473': OrderedDict([('Avg(%)', 87.8716)])}"
19,20,symmetric_with_uint8,Percentile,True,99.9999,86.4803,"{'473': OrderedDict([('Avg(%)', 86.4803)])}"
20,21,symmetric_with_uint8,Percentile,False,99.9,62.9380,"{'473': OrderedDict([('Avg(%)', 62.938)])}"
21,22,symmetric_with_uint8,Percentile,False,99.99,67.0612,"{'473': OrderedDict([('Avg(%)', 67.0612)])}"
22,23,symmetric_with_uint8,Percentile,False,99.999,67.3830,"{'473': OrderedDict([('Avg(%)', 67.383)])}"
23,24,symmetric_with_uint8,Percentile,False,99.9999,68.8547,"{'473': OrderedDict([('Avg(%)', 68.8547)])}"

# Oneshot Snooping
In this snooping mode, on a single run user can configure the tool to dump all intermediate layer activations of the model on AIC and compare them with golden outputs using one or more in built or custom comparators.

![flow](images/oneshot_flow.png)

Below image gives a view of sample model transformation in oneshot snooping
![flow](images/oneshot_model_tranforms.png)

### Executing the oneshot run of Accuracy Analyzer tool

In [9]:

!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
           -reference onnxrt \
           -snooping oneshot \
           -comparator cos \
           -tol-thres 0.01 \
           -model {model_path} \
           -input-list {list_file} \
           -work-dir 'log_dir/oneshot_log_dir' \
           -skip-initial-run \
           -precision int8 \
           -device-id {device_id} \ 
           -silent

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/home/adarisi/ml-tools/qaic-pytools-dist/env/lib64/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/oneshot_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
                 Layer Type              Shape Activations (min,max,median)  CosineSimilarity(%) Info
O/P Name
473                 (*)Gemm          (1, 1000)      (-7.962, 14.355, -0.18)              97.9618    -
317                    Clip  (1, 32, 112, 112)          (0.0, 2.962, 0.244)              99.9910    -
320                    Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)              99.9211    -
322                    Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)              99.0808    -
325                    Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)              99.6197    -
328                    Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)              99.5633    -
330                    Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)              98.0539    -
333                    Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)              99.2253    -
336                    Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)              99.3462    -
338                    Conv    (1, 24, 56, 56)      (-3.349, 3.994, -0.009)              98.5688    -
339                     Add    (1, 24, 56, 56)      (-4.153, 5.757, -0.012)              98.4207    -
342                    Clip   (1, 144, 56, 56)          (0.0, 1.796, 0.073)              99.0903    -
345                    Clip   (1, 144, 28, 28)          (0.0, 2.466, 0.145)              98.9813    -
347                    Conv    (1, 32, 28, 28)       (-2.48, 2.348, -0.021)              97.0375    -
350                    Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)              98.7763    -
353                    Clip   (1, 192, 28, 28)            (0.0, 1.581, 0.0)              98.2542    -
355                    Conv    (1, 32, 28, 28)        (-2.185, 2.339, 0.01)              95.9288    -
356                     Add    (1, 32, 28, 28)      (-3.093, 3.128, -0.002)              97.4012    -
359                    Clip   (1, 192, 28, 28)           (0.0, 1.247, 0.09)              99.0828    -
362                    Clip   (1, 192, 28, 28)            (0.0, 1.605, 0.0)              98.8016    -
364                    Conv    (1, 32, 28, 28)       (-2.256, 1.801, 0.001)              97.2395    -
365                     Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)              97.4764    -
368                    Clip   (1, 192, 28, 28)           (0.0, 1.45, 0.067)              98.7229    -
371                    Clip   (1, 192, 14, 14)          (0.0, 1.977, 0.204)              99.1829    -
373                    Conv    (1, 64, 14, 14)      (-1.992, 2.155, -0.019)              96.8835    -
376                    Clip   (1, 384, 14, 14)          (0.0, 0.875, 0.102)              98.6176    -
379                    Clip   (1, 384, 14, 14)            (0.0, 1.127, 0.0)              97.8021    -
381                    Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)              97.6865    -
382                     Add    (1, 64, 14, 14)       (-2.24, 2.105, -0.009)              97.7190    -
385                    Clip   (1, 384, 14, 14)          (0.0, 0.685, 0.059)              99.0514    -
388                    Clip   (1, 384, 14, 14)            (0.0, 1.354, 0.0)              98.4992    -
390                    Conv    (1, 64, 14, 14)       (-1.337, 1.224, 0.013)              97.5513    -
391                     Add    (1, 64, 14, 14)       (-2.812, 2.493, 0.001)              97.6593    -
394                    Clip   (1, 384, 14, 14)          (0.0, 0.687, 0.029)              98.9415    -
397                    Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)              98.6444    -
399                    Conv    (1, 64, 14, 14)       (-1.239, 1.442, 0.004)              97.3742    -
400                     Add    (1, 64, 14, 14)       (-2.687, 2.424, 0.003)              97.3333    -
403                    Clip   (1, 384, 14, 14)          (0.0, 0.904, 0.072)              98.9094    -
406                    Clip   (1, 384, 14, 14)          (0.0, 1.945, 0.071)              98.7108    -
408                    Conv    (1, 96, 14, 14)       (-2.516, 2.143, 0.005)              97.4191    -
411                    Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)              98.7853    -
414                    Clip   (1, 576, 14, 14)            (0.0, 2.021, 0.0)              98.4371    -
416                    Conv    (1, 96, 14, 14)      (-1.555, 1.738, -0.002)              97.3198    -
417                     Add    (1, 96, 14, 14)       (-2.622, 2.259, 0.008)              97.4924    -
420                    Clip   (1, 576, 14, 14)            (0.0, 0.939, 0.0)              98.6834    -
423                    Clip   (1, 576, 14, 14)            (0.0, 2.862, 0.0)              98.4887    -
425                    Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)              97.0035    -
426                     Add    (1, 96, 14, 14)        (-4.119, 2.87, 0.009)              97.3898    -
429                    Clip   (1, 576, 14, 14)            (0.0, 1.563, 0.0)              98.1970    -
432                    Clip     (1, 576, 7, 7)          (0.0, 2.461, 0.052)              99.2562    -
434                    Conv     (1, 160, 7, 7)         (-1.268, 1.213, 0.0)              97.5858    -
437                    Clip     (1, 960, 7, 7)          (0.0, 1.469, 0.036)              98.9296    -
440                    Clip     (1, 960, 7, 7)             (0.0, 2.29, 0.0)              98.7200    -
442                    Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)              97.5767    -
443                     Add     (1, 160, 7, 7)       (-1.563, 1.335, 0.018)              97.7363    -
446                    Clip     (1, 960, 7, 7)          (0.0, 1.054, 0.013)              99.0359    -
449                    Clip     (1, 960, 7, 7)             (0.0, 1.57, 0.0)              98.6771    -
451                    Conv     (1, 160, 7, 7)       (-1.429, 1.725, 0.001)              97.1006    -
452                     Add     (1, 160, 7, 7)       (-2.275, 2.112, 0.018)              97.2838    -
455                    Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)              98.5821    -
458                    Clip     (1, 960, 7, 7)           (0.0, 1.35, 0.037)              99.3783    -
460                    Conv     (1, 320, 7, 7)        (-1.671, 1.232, -0.0)              96.6575    -
463                    Clip    (1, 1280, 7, 7)              (0.0, 6.0, 0.0)              97.2169    -
464       GlobalAveragePool    (1, 1280, 1, 1)           (0.0, 2.836, 0.42)              98.5525    -
472                 Reshape          (1, 1280)           (0.0, 2.836, 0.42)              98.5524    -
Results saved at log_dir/oneshot_log_dir/oneshot.csv
INFO: qaic-acc-analyzer ended successfully

### Oneshot result:

In [67]:

pd.set_option("display.max_rows", None, "display.max_columns", None)
csv_path = os.path.join(cwd,'log_dir/oneshot_log_dir/oneshot.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Layer Type,Shape,"Activations (min,max,median)",CosineSimilarity(%),Info
0,473,(*)Gemm,"(1, 1000)","(-7.962, 14.355, -0.18)",97.9618,-
1,317,Clip,"(1, 32, 112, 112)","(0.0, 2.962, 0.244)",99.9911,-
2,320,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",99.9216,-
3,322,Conv,"(1, 16, 112, 112)","(-6.109, 5.047, -0.001)",99.0808,-
4,325,Clip,"(1, 96, 112, 112)","(0.0, 4.287, 0.154)",99.6197,-
5,328,Clip,"(1, 96, 56, 56)","(0.0, 3.188, 0.098)",99.5639,-
6,330,Conv,"(1, 24, 56, 56)","(-2.589, 3.013, -0.01)",98.0537,-
7,333,Clip,"(1, 144, 56, 56)","(0.0, 1.068, 0.13)",99.2260,-
8,336,Clip,"(1, 144, 56, 56)","(0.0, 2.844, 0.047)",99.3472,-
9,338,Conv,"(1, 24, 56, 56)","(-3.349, 3.994, -0.009)",98.5688,-
10,339,Add,"(1, 24, 56, 56)","(-4.153, 5.757, -0.012)",98.4206,-
11,342,Clip,"(1, 144, 56, 56)","(0.0, 1.796, 0.073)",99.0898,-
12,345,Clip,"(1, 144, 28, 28)","(0.0, 2.466, 0.145)",98.9812,-
13,347,Conv,"(1, 32, 28, 28)","(-2.48, 2.348, -0.021)",97.0375,-
14,350,Clip,"(1, 192, 28, 28)","(0.0, 1.007, 0.135)",98.7763,-
15,353,Clip,"(1, 192, 28, 28)","(0.0, 1.581, 0.0)",98.2542,-
16,355,Conv,"(1, 32, 28, 28)","(-2.185, 2.339, 0.01)",95.9288,-
17,356,Add,"(1, 32, 28, 28)","(-3.093, 3.128, -0.002)",97.4012,-
18,359,Clip,"(1, 192, 28, 28)","(0.0, 1.247, 0.09)",99.0825,-
19,362,Clip,"(1, 192, 28, 28)","(0.0, 1.605, 0.0)",98.8015,-
20,364,Conv,"(1, 32, 28, 28)","(-2.256, 1.801, 0.001)",97.2394,-
21,365,Add,"(1, 32, 28, 28)","(-4.036, 3.924, -0.003)",97.4763,-
22,368,Clip,"(1, 192, 28, 28)","(0.0, 1.45, 0.067)",98.7229,-
23,371,Clip,"(1, 192, 14, 14)","(0.0, 1.977, 0.204)",99.1829,-
24,373,Conv,"(1, 64, 14, 14)","(-1.992, 2.155, -0.019)",96.8835,-
25,376,Clip,"(1, 384, 14, 14)","(0.0, 0.875, 0.102)",98.6174,-
26,379,Clip,"(1, 384, 14, 14)","(0.0, 1.127, 0.0)",97.8020,-
27,381,Conv,"(1, 64, 14, 14)","(-1.842, 1.862, 0.011)",97.6865,-
28,382,Add,"(1, 64, 14, 14)","(-2.24, 2.105, -0.009)",97.7190,-
29,385,Clip,"(1, 384, 14, 14)","(0.0, 0.685, 0.059)",99.0515,-
30,388,Clip,"(1, 384, 14, 14)","(0.0, 1.354, 0.0)",98.4992,-
31,390,Conv,"(1, 64, 14, 14)","(-1.337, 1.224, 0.013)",97.5513,-
32,391,Add,"(1, 64, 14, 14)","(-2.812, 2.493, 0.001)",97.6593,-
33,394,Clip,"(1, 384, 14, 14)","(0.0, 0.687, 0.029)",98.9415,-
34,397,Clip,"(1, 384, 14, 14)","(0.0, 1.319, 0.0)",98.6443,-
35,399,Conv,"(1, 64, 14, 14)","(-1.239, 1.442, 0.004)",97.3742,-
36,400,Add,"(1, 64, 14, 14)","(-2.687, 2.424, 0.003)",97.3333,-
37,403,Clip,"(1, 384, 14, 14)","(0.0, 0.904, 0.072)",98.9092,-
38,406,Clip,"(1, 384, 14, 14)","(0.0, 1.945, 0.071)",98.7108,-
39,408,Conv,"(1, 96, 14, 14)","(-2.516, 2.143, 0.005)",97.4191,-
40,411,Clip,"(1, 576, 14, 14)","(0.0, 1.124, 0.01)",98.7851,-
41,414,Clip,"(1, 576, 14, 14)","(0.0, 2.021, 0.0)",98.4370,-
42,416,Conv,"(1, 96, 14, 14)","(-1.555, 1.738, -0.002)",97.3197,-
43,417,Add,"(1, 96, 14, 14)","(-2.622, 2.259, 0.008)",97.4924,-
44,420,Clip,"(1, 576, 14, 14)","(0.0, 0.939, 0.0)",98.6833,-
45,423,Clip,"(1, 576, 14, 14)","(0.0, 2.862, 0.0)",98.4887,-
46,425,Conv,"(1, 96, 14, 14)","(-2.265, 2.364, 0.006)",97.0035,-
47,426,Add,"(1, 96, 14, 14)","(-4.119, 2.87, 0.009)",97.3898,-
48,429,Clip,"(1, 576, 14, 14)","(0.0, 1.563, 0.0)",98.1970,-
49,432,Clip,"(1, 576, 7, 7)","(0.0, 2.461, 0.052)",99.2562,-
50,434,Conv,"(1, 160, 7, 7)","(-1.268, 1.213, 0.0)",97.5858,-
51,437,Clip,"(1, 960, 7, 7)","(0.0, 1.469, 0.036)",98.9296,-
52,440,Clip,"(1, 960, 7, 7)","(0.0, 2.29, 0.0)",98.7200,-
53,442,Conv,"(1, 160, 7, 7)","(-1.003, 0.807, 0.015)",97.5767,-
54,443,Add,"(1, 160, 7, 7)","(-1.563, 1.335, 0.018)",97.7363,-
55,446,Clip,"(1, 960, 7, 7)","(0.0, 1.054, 0.013)",99.0359,-
56,449,Clip,"(1, 960, 7, 7)","(0.0, 1.57, 0.0)",98.6771,-
57,451,Conv,"(1, 160, 7, 7)","(-1.429, 1.725, 0.001)",97.1006,-
58,452,Add,"(1, 160, 7, 7)","(-2.275, 2.112, 0.018)",97.2838,-
59,455,Clip,"(1, 960, 7, 7)","(0.0, 0.882, 0.0)",98.5821,-
60,458,Clip,"(1, 960, 7, 7)","(0.0, 1.35, 0.037)",99.3783,-
61,460,Conv,"(1, 320, 7, 7)","(-1.671, 1.232, -0.0)",96.6575,-
62,463,Clip,"(1, 1280, 7, 7)","(0.0, 6.0, 0.0)",97.2169,-
63,464,GlobalAveragePool,"(1, 1280, 1, 1)","(0.0, 2.836, 0.42)",98.5525,-
64,472,Reshape,"(1, 1280)","(0.0, 2.836, 0.42)",98.5524,-

# Layerwise Snooping
In Layerwise debugging, the debugger debugs one layer at a time.  The reference activations for all the layers are collected first by running the model on a reference platform.

Next, layer outputs are enabled one a time, the model is compiled and executed on AIC in an iterative manner. Just like Oneshot snooping, currently the debugger modifies the original model to enable the intermediate output nodes.

The AIC outputs are compared with the reference for the added layer and the original outputs - in each iteration (using one or more comparators).

If the comparison resulted in a mismatch with reference, the debugger partitions the model after that layer and feeds the reference output for that layer to the new model and the debugging process continues with the new model.

Since there is compilation (additionally profile generation when run in quantized int8 precision) followed by execution at each layer, the debugging process is time consuming. There are multiple options which can be used to speed up this debugging process like starting to debug from a specific layer, skipping layer types, top-partition mode, etc.. as described in the debugging options section.

![flow](images/layerwise_flow.png)

Below image gives a view of sample model transformations in each iteration of layerwise snooping

![flow](images/layerwise_model_transforms.PNG)

## Executing the layerwise run of Accuracy Analyzer tool

In [91]:

!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                -reference onnxrt \
                -snooping layerwise \
                -comparator cos \
                -tol-thres 0.01 \
                -model {model_path} \
                -input-list {list_file} \
                -work-dir 'log_dir/layerwise_log_dir' \
                -skip-initial-run \
                -precision int8 \
                -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
[================================================================================] 100.0% (65/65, skipped:0)
         Status         Layer Type              Shape Activations (Min,Max,Median)  CosineSimilarity(%)                   Orig Outputs Info
O/P Name
317        part               Clip  (1, 32, 112, 112)          (0.0, 2.962, 0.244)              99.9911  {'473': {'CosineSimilarity...    -
320        part               Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)              99.9290  {'473': {'CosineSimilarity...    -
322        part               Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)              99.9467  {'473': {'CosineSimilarity...    -
325        part               Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)              99.9758  {'473': {'CosineSimilarity...    -
328        part               Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)              99.9633  {'473': {'CosineSimilarity...    -
330        part               Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)              99.9802  {'473': {'CosineSimilarity...    -
333        part               Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)              99.9901  {'473': {'CosineSimilarity...    -
336        part               Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)              99.9798  {'473': {'CosineSimilarity...    -
338        part               Conv    (1, 24, 56, 56)      (-3.349, 3.994, -0.009)              99.9787  {'473': {'CosineSimilarity...    -
339        part                Add    (1, 24, 56, 56)      (-4.153, 5.757, -0.012)              99.9845  {'473': {'CosineSimilarity...    -
342        part               Clip   (1, 144, 56, 56)          (0.0, 1.796, 0.073)              99.9841  {'473': {'CosineSimilarity...    -
345        part               Clip   (1, 144, 28, 28)          (0.0, 2.466, 0.145)              99.9845  {'473': {'CosineSimilarity...    -
347        part               Conv    (1, 32, 28, 28)       (-2.48, 2.348, -0.021)              99.9876  {'473': {'CosineSimilarity...    -
350        part               Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)              99.9910  {'473': {'CosineSimilarity...    -
353        part               Clip   (1, 192, 28, 28)            (0.0, 1.581, 0.0)              99.9566  {'473': {'CosineSimilarity...    -
355        part               Conv    (1, 32, 28, 28)        (-2.185, 2.339, 0.01)              99.9841  {'473': {'CosineSimilarity...    -
356        part                Add    (1, 32, 28, 28)      (-3.093, 3.128, -0.002)              99.9922  {'473': {'CosineSimilarity...    -
359        part               Clip   (1, 192, 28, 28)           (0.0, 1.247, 0.09)              99.9856  {'473': {'CosineSimilarity...    -
362        part               Clip   (1, 192, 28, 28)            (0.0, 1.605, 0.0)              99.9773  {'473': {'CosineSimilarity...    -
364        part               Conv    (1, 32, 28, 28)       (-2.256, 1.801, 0.001)              99.9751  {'473': {'CosineSimilarity...    -
365        part                Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)              99.9915  {'473': {'CosineSimilarity...    -
368        part               Clip   (1, 192, 28, 28)           (0.0, 1.45, 0.067)              99.9863  {'473': {'CosineSimilarity...    -
371        part               Clip   (1, 192, 14, 14)          (0.0, 1.977, 0.204)              99.9947  {'473': {'CosineSimilarity...    -
373        part               Conv    (1, 64, 14, 14)      (-1.992, 2.155, -0.019)              99.9857  {'473': {'CosineSimilarity...    -
376        part               Clip   (1, 384, 14, 14)          (0.0, 0.875, 0.102)              99.9879  {'473': {'CosineSimilarity...    -
379        part               Clip   (1, 384, 14, 14)            (0.0, 1.127, 0.0)              99.9667  {'473': {'CosineSimilarity...    -
381        part               Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)              99.9859  {'473': {'CosineSimilarity...    -
382        part                Add    (1, 64, 14, 14)       (-2.24, 2.105, -0.009)              99.9932  {'473': {'CosineSimilarity...    -
385        part               Clip   (1, 384, 14, 14)          (0.0, 0.685, 0.059)              99.9838  {'473': {'CosineSimilarity...    -
388        part               Clip   (1, 384, 14, 14)            (0.0, 1.354, 0.0)              99.9401  {'473': {'CosineSimilarity...    -
390        part               Conv    (1, 64, 14, 14)       (-1.337, 1.224, 0.013)              99.9808  {'473': {'CosineSimilarity...    -
391        part                Add    (1, 64, 14, 14)       (-2.812, 2.493, 0.001)              99.9934  {'473': {'CosineSimilarity...    -
394        part               Clip   (1, 384, 14, 14)          (0.0, 0.687, 0.029)              99.9837  {'473': {'CosineSimilarity...    -
397        part               Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)              99.9831  {'473': {'CosineSimilarity...    -
399        part               Conv    (1, 64, 14, 14)       (-1.239, 1.442, 0.004)              99.9763  {'473': {'CosineSimilarity...    -
400        part                Add    (1, 64, 14, 14)       (-2.687, 2.424, 0.003)              99.9927  {'473': {'CosineSimilarity...    -
403        part               Clip   (1, 384, 14, 14)          (0.0, 0.904, 0.072)              99.9875  {'473': {'CosineSimilarity...    -
406        part               Clip   (1, 384, 14, 14)          (0.0, 1.945, 0.071)              99.9836  {'473': {'CosineSimilarity...    -
408        part               Conv    (1, 96, 14, 14)       (-2.516, 2.143, 0.005)              99.9829  {'473': {'CosineSimilarity...    -
411        part               Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)              99.9804  {'473': {'CosineSimilarity...    -
414        part               Clip   (1, 576, 14, 14)            (0.0, 2.021, 0.0)              99.9646  {'473': {'CosineSimilarity...    -
416        part               Conv    (1, 96, 14, 14)      (-1.555, 1.738, -0.002)              99.9808  {'473': {'CosineSimilarity...    -
417        part                Add    (1, 96, 14, 14)       (-2.622, 2.259, 0.008)              99.9902  {'473': {'CosineSimilarity...    -
420        part               Clip   (1, 576, 14, 14)            (0.0, 0.939, 0.0)              99.9758  {'473': {'CosineSimilarity...    -
423        part               Clip   (1, 576, 14, 14)            (0.0, 2.862, 0.0)              99.9745  {'473': {'CosineSimilarity...    -
425        part               Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)              99.9564  {'473': {'CosineSimilarity...    -
426        part                Add    (1, 96, 14, 14)        (-4.119, 2.87, 0.009)              99.9888  {'473': {'CosineSimilarity...    -
429        part               Clip   (1, 576, 14, 14)            (0.0, 1.563, 0.0)              99.9774  {'473': {'CosineSimilarity...    -
432        part               Clip     (1, 576, 7, 7)          (0.0, 2.461, 0.052)              99.9914  {'473': {'CosineSimilarity...    -
434        part               Conv     (1, 160, 7, 7)         (-1.268, 1.213, 0.0)              99.9719  {'473': {'CosineSimilarity...    -
437        part               Clip     (1, 960, 7, 7)          (0.0, 1.469, 0.036)              99.9755  {'473': {'CosineSimilarity...    -
440        part               Clip     (1, 960, 7, 7)             (0.0, 2.29, 0.0)              99.9531  {'473': {'CosineSimilarity...    -
442        part               Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)              99.9678  {'473': {'CosineSimilarity...    -
443        part                Add     (1, 160, 7, 7)       (-1.563, 1.335, 0.018)              99.9869  {'473': {'CosineSimilarity...    -
446        part               Clip     (1, 960, 7, 7)          (0.0, 1.054, 0.013)              99.9808  {'473': {'CosineSimilarity...    -
449        part               Clip     (1, 960, 7, 7)             (0.0, 1.57, 0.0)              99.9770  {'473': {'CosineSimilarity...    -
451        part               Conv     (1, 160, 7, 7)       (-1.429, 1.725, 0.001)              99.9686  {'473': {'CosineSimilarity...    -
452        part                Add     (1, 160, 7, 7)       (-2.275, 2.112, 0.018)              99.9881  {'473': {'CosineSimilarity...    -
455        part               Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)              99.9672  {'473': {'CosineSimilarity...    -
458        part               Clip     (1, 960, 7, 7)           (0.0, 1.35, 0.037)              99.9831  {'473': {'CosineSimilarity...    -
460        part               Conv     (1, 320, 7, 7)        (-1.671, 1.232, -0.0)              99.9508  {'473': {'CosineSimilarity...    -
463        part               Clip    (1, 1280, 7, 7)              (0.0, 6.0, 0.0)              99.9922  {'473': {'CosineSimilarity...    -
464        part  GlobalAveragePool    (1, 1280, 1, 1)           (0.0, 2.836, 0.42)              99.9987  {'473': {'CosineSimilarity...    -
472        part            Reshape          (1, 1280)           (0.0, 2.836, 0.42)             100.0000  {'473': {'CosineSimilarity...    -
473                        (*)Gemm          (1, 1000)      (-7.962, 14.355, -0.18)              99.9945  {'473': {'CosineSimilarity...    -
Results saved at log_dir/layerwise_log_dir/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise result:

In [92]:
csv_path = os.path.join(cwd , 'log_dir/layerwise_log_dir/layerwise.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Status,Layer Type,Shape,"Activations (Min,Max,Median)",CosineSimilarity(%),Orig Outputs,Info
0,317,part,Clip,"(1, 32, 112, 112)","(0.0, 2.962, 0.244)",99.9911,{'473': {'CosineSimilarity(%)': 97.9618}},-
1,320,part,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",99.9290,{'473': {'CosineSimilarity(%)': 98.024}},-
2,322,part,Conv,"(1, 16, 112, 112)","(-6.109, 5.047, -0.001)",99.9467,{'473': {'CosineSimilarity(%)': 99.2711}},-
3,325,part,Clip,"(1, 96, 112, 112)","(0.0, 4.287, 0.154)",99.9758,{'473': {'CosineSimilarity(%)': 99.2837}},-
4,328,part,Clip,"(1, 96, 56, 56)","(0.0, 3.188, 0.098)",99.9633,{'473': {'CosineSimilarity(%)': 99.268}},-
5,330,part,Conv,"(1, 24, 56, 56)","(-2.589, 3.013, -0.01)",99.9802,{'473': {'CosineSimilarity(%)': 99.5101}},-
6,333,part,Clip,"(1, 144, 56, 56)","(0.0, 1.068, 0.13)",99.9901,{'473': {'CosineSimilarity(%)': 99.5233}},-
7,336,part,Clip,"(1, 144, 56, 56)","(0.0, 2.844, 0.047)",99.9798,{'473': {'CosineSimilarity(%)': 99.4945}},-
8,338,part,Conv,"(1, 24, 56, 56)","(-3.349, 3.994, -0.009)",99.9787,{'473': {'CosineSimilarity(%)': 99.546}},-
9,339,part,Add,"(1, 24, 56, 56)","(-4.153, 5.757, -0.012)",99.9845,{'473': {'CosineSimilarity(%)': 99.5535}},-
10,342,part,Clip,"(1, 144, 56, 56)","(0.0, 1.796, 0.073)",99.9841,{'473': {'CosineSimilarity(%)': 99.5588}},-
11,345,part,Clip,"(1, 144, 28, 28)","(0.0, 2.466, 0.145)",99.9845,{'473': {'CosineSimilarity(%)': 99.6207}},-
12,347,part,Conv,"(1, 32, 28, 28)","(-2.48, 2.348, -0.021)",99.9876,{'473': {'CosineSimilarity(%)': 99.7429}},-
13,350,part,Clip,"(1, 192, 28, 28)","(0.0, 1.007, 0.135)",99.9910,{'473': {'CosineSimilarity(%)': 99.7624}},-
14,353,part,Clip,"(1, 192, 28, 28)","(0.0, 1.581, 0.0)",99.9566,{'473': {'CosineSimilarity(%)': 99.7318}},-
15,355,part,Conv,"(1, 32, 28, 28)","(-2.185, 2.339, 0.01)",99.9841,{'473': {'CosineSimilarity(%)': 99.7633}},-
16,356,part,Add,"(1, 32, 28, 28)","(-3.093, 3.128, -0.002)",99.9922,{'473': {'CosineSimilarity(%)': 99.7357}},-
17,359,part,Clip,"(1, 192, 28, 28)","(0.0, 1.247, 0.09)",99.9856,{'473': {'CosineSimilarity(%)': 99.7548}},-
18,362,part,Clip,"(1, 192, 28, 28)","(0.0, 1.605, 0.0)",99.9773,{'473': {'CosineSimilarity(%)': 99.7295}},-
19,364,part,Conv,"(1, 32, 28, 28)","(-2.256, 1.801, 0.001)",99.9751,{'473': {'CosineSimilarity(%)': 99.746}},-
20,365,part,Add,"(1, 32, 28, 28)","(-4.036, 3.924, -0.003)",99.9915,{'473': {'CosineSimilarity(%)': 99.715}},-
21,368,part,Clip,"(1, 192, 28, 28)","(0.0, 1.45, 0.067)",99.9863,{'473': {'CosineSimilarity(%)': 99.766}},-
22,371,part,Clip,"(1, 192, 14, 14)","(0.0, 1.977, 0.204)",99.9947,{'473': {'CosineSimilarity(%)': 99.7432}},-
23,373,part,Conv,"(1, 64, 14, 14)","(-1.992, 2.155, -0.019)",99.9857,{'473': {'CosineSimilarity(%)': 99.7329}},-
24,376,part,Clip,"(1, 384, 14, 14)","(0.0, 0.875, 0.102)",99.9879,{'473': {'CosineSimilarity(%)': 99.708}},-
25,379,part,Clip,"(1, 384, 14, 14)","(0.0, 1.127, 0.0)",99.9667,{'473': {'CosineSimilarity(%)': 99.7163}},-
26,381,part,Conv,"(1, 64, 14, 14)","(-1.842, 1.862, 0.011)",99.9859,{'473': {'CosineSimilarity(%)': 99.7229}},-
27,382,part,Add,"(1, 64, 14, 14)","(-2.24, 2.105, -0.009)",99.9932,{'473': {'CosineSimilarity(%)': 99.7577}},-
28,385,part,Clip,"(1, 384, 14, 14)","(0.0, 0.685, 0.059)",99.9838,{'473': {'CosineSimilarity(%)': 99.7767}},-
29,388,part,Clip,"(1, 384, 14, 14)","(0.0, 1.354, 0.0)",99.9401,{'473': {'CosineSimilarity(%)': 99.7231}},-
30,390,part,Conv,"(1, 64, 14, 14)","(-1.337, 1.224, 0.013)",99.9808,{'473': {'CosineSimilarity(%)': 99.7718}},-
31,391,part,Add,"(1, 64, 14, 14)","(-2.812, 2.493, 0.001)",99.9934,{'473': {'CosineSimilarity(%)': 99.8226}},-
32,394,part,Clip,"(1, 384, 14, 14)","(0.0, 0.687, 0.029)",99.9837,{'473': {'CosineSimilarity(%)': 99.7929}},-
33,397,part,Clip,"(1, 384, 14, 14)","(0.0, 1.319, 0.0)",99.9831,{'473': {'CosineSimilarity(%)': 99.7851}},-
34,399,part,Conv,"(1, 64, 14, 14)","(-1.239, 1.442, 0.004)",99.9763,{'473': {'CosineSimilarity(%)': 99.7765}},-
35,400,part,Add,"(1, 64, 14, 14)","(-2.687, 2.424, 0.003)",99.9927,{'473': {'CosineSimilarity(%)': 99.8115}},-
36,403,part,Clip,"(1, 384, 14, 14)","(0.0, 0.904, 0.072)",99.9875,{'473': {'CosineSimilarity(%)': 99.7834}},-
37,406,part,Clip,"(1, 384, 14, 14)","(0.0, 1.945, 0.071)",99.9836,{'473': {'CosineSimilarity(%)': 99.772}},-
38,408,part,Conv,"(1, 96, 14, 14)","(-2.516, 2.143, 0.005)",99.9829,{'473': {'CosineSimilarity(%)': 99.8321}},-
39,411,part,Clip,"(1, 576, 14, 14)","(0.0, 1.124, 0.01)",99.9804,{'473': {'CosineSimilarity(%)': 99.8442}},-
40,414,part,Clip,"(1, 576, 14, 14)","(0.0, 2.021, 0.0)",99.9646,{'473': {'CosineSimilarity(%)': 99.8422}},-
41,416,part,Conv,"(1, 96, 14, 14)","(-1.555, 1.738, -0.002)",99.9808,{'473': {'CosineSimilarity(%)': 99.8533}},-
42,417,part,Add,"(1, 96, 14, 14)","(-2.622, 2.259, 0.008)",99.9902,{'473': {'CosineSimilarity(%)': 99.8091}},-
43,420,part,Clip,"(1, 576, 14, 14)","(0.0, 0.939, 0.0)",99.9758,{'473': {'CosineSimilarity(%)': 99.8473}},-
44,423,part,Clip,"(1, 576, 14, 14)","(0.0, 2.862, 0.0)",99.9745,{'473': {'CosineSimilarity(%)': 99.8364}},-
45,425,part,Conv,"(1, 96, 14, 14)","(-2.265, 2.364, 0.006)",99.9564,{'473': {'CosineSimilarity(%)': 99.8481}},-
46,426,part,Add,"(1, 96, 14, 14)","(-4.119, 2.87, 0.009)",99.9888,{'473': {'CosineSimilarity(%)': 99.8414}},-
47,429,part,Clip,"(1, 576, 14, 14)","(0.0, 1.563, 0.0)",99.9774,{'473': {'CosineSimilarity(%)': 99.8258}},-
48,432,part,Clip,"(1, 576, 7, 7)","(0.0, 2.461, 0.052)",99.9914,{'473': {'CosineSimilarity(%)': 99.856}},-
49,434,part,Conv,"(1, 160, 7, 7)","(-1.268, 1.213, 0.0)",99.9719,{'473': {'CosineSimilarity(%)': 99.8436}},-
50,437,part,Clip,"(1, 960, 7, 7)","(0.0, 1.469, 0.036)",99.9755,{'473': {'CosineSimilarity(%)': 99.8631}},-
51,440,part,Clip,"(1, 960, 7, 7)","(0.0, 2.29, 0.0)",99.9531,{'473': {'CosineSimilarity(%)': 99.8621}},-
52,442,part,Conv,"(1, 160, 7, 7)","(-1.003, 0.807, 0.015)",99.9678,{'473': {'CosineSimilarity(%)': 99.9084}},-
53,443,part,Add,"(1, 160, 7, 7)","(-1.563, 1.335, 0.018)",99.9869,{'473': {'CosineSimilarity(%)': 99.9151}},-
54,446,part,Clip,"(1, 960, 7, 7)","(0.0, 1.054, 0.013)",99.9808,{'473': {'CosineSimilarity(%)': 99.9182}},-
55,449,part,Clip,"(1, 960, 7, 7)","(0.0, 1.57, 0.0)",99.9770,{'473': {'CosineSimilarity(%)': 99.9072}},-
56,451,part,Conv,"(1, 160, 7, 7)","(-1.429, 1.725, 0.001)",99.9686,{'473': {'CosineSimilarity(%)': 99.9323}},-
57,452,part,Add,"(1, 160, 7, 7)","(-2.275, 2.112, 0.018)",99.9881,{'473': {'CosineSimilarity(%)': 99.9502}},-
58,455,part,Clip,"(1, 960, 7, 7)","(0.0, 0.882, 0.0)",99.9672,{'473': {'CosineSimilarity(%)': 99.9606}},-
59,458,part,Clip,"(1, 960, 7, 7)","(0.0, 1.35, 0.037)",99.9831,{'473': {'CosineSimilarity(%)': 99.9632}},-
60,460,part,Conv,"(1, 320, 7, 7)","(-1.671, 1.232, -0.0)",99.9508,{'473': {'CosineSimilarity(%)': 99.9758}},-
61,463,part,Clip,"(1, 1280, 7, 7)","(0.0, 6.0, 0.0)",99.9922,{'473': {'CosineSimilarity(%)': 99.9938}},-
62,464,part,GlobalAveragePool,"(1, 1280, 1, 1)","(0.0, 2.836, 0.42)",99.9987,{'473': {'CosineSimilarity(%)': 99.9945}},-
63,472,part,Reshape,"(1, 1280)","(0.0, 2.836, 0.42)",100.0000,{'473': {'CosineSimilarity(%)': 99.9946}},-
64,473,NaN,(*)Gemm,"(1, 1000)","(-7.962, 14.355, -0.18)",99.9945,{'473': {'CosineSimilarity(%)': 99.9945}},-

### Graphical result of layerwise run
Below is the plot between nodes vs cosine similarity value between aic model output and onnxrt model output  
![plot](images/demo_plot_2.png)

## Executing layerwise run to extract sub-graph
   This run extracts the subgraph from model at specified start and end layers

In [68]:

!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                -reference onnxrt \
                -snooping layerwise \
                -comparator cos \
                -tol-thres 0.01 \
                -model {model_path} \
                -input-list {list_file} \
                -work-dir 'log_dir/layerwise_extract_log_dir' \
                -skip-initial-run \
                -precision int8 \
                -start-from-layer-output 371 \
                -end-layer-output 379 \
                -extract \
                -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_extract_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Extracting sub-graph at specified start and end layers....
INFO: Extracted sub-graph is saved at log_dir/layerwise_extract_log_dir/partitions/extracted_model.onnx

## Executing layerwise run on sub-graph 
 This run gives the layerwise snooping results on specified sub-graph of model

In [70]:

!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                -reference onnxrt \
                -snooping layerwise \
                -comparator cos \
                -tol-thres 0.01 \
                -model {model_path} \
                -input-list {list_file} \
                -work-dir 'log_dir/layerwise_subgraph_log_dir' \
                -skip-initial-run \
                -precision int8 \
                -start-from-layer-output 371 \
                -end-layer-output 379 \
                -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_subgraph_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
[================================================================================] 100.0% (3/3, skipped:0)
         Status Layer Type             Shape Activations (Min,Max,Median)  CosineSimilarity(%)                   Orig Outputs Info
O/P Name
373        part       Conv   (1, 64, 14, 14)      (-1.992, 2.155, -0.019)              99.9857  {'379': {'CosineSimilarity...    -
376        part       Clip  (1, 384, 14, 14)          (0.0, 0.875, 0.102)              99.9879  {'379': {'CosineSimilarity...    -
379                (*)Clip  (1, 384, 14, 14)            (0.0, 1.127, 0.0)              99.9667  {'379': {'CosineSimilarity...    -
Results saved at log_dir/layerwise_subgraph_log_dir/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise run result

In [74]:
csv_path = os.path.join(cwd, 'log_dir/layerwise_subgraph_log_dir/layerwise.csv')
df=pd.read_csv(csv_path)
df.fillna('', inplace=True)
df

,O/P Name,Status,Layer Type,Shape,"Activations (Min,Max,Median)",CosineSimilarity(%),Orig Outputs,Info
0,373,part,Conv,"(1, 64, 14, 14)","(-1.992, 2.155, -0.019)",99.9857,{'379': {'CosineSimilarity(%)': 99.9562}},-
1,376,part,Clip,"(1, 384, 14, 14)","(0.0, 0.875, 0.102)",99.9879,{'379': {'CosineSimilarity(%)': 99.9605}},-
2,379,,(*)Clip,"(1, 384, 14, 14)","(0.0, 1.127, 0.0)",99.9667,{'379': {'CosineSimilarity(%)': 99.9667}},-

## Executing Layerwise snooping on specific op type
This run gives the layerwise snooping only on specific op type (Add) of model

*Note: User can use **-add-layer-outputs** option to specify particular node to be debugged*

In [75]:

!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                 -reference onnxrt \
                 -snooping layerwise \
                 -comparator cos \
                 -tol-thres 0.01 \
                 -model {model_path} \
                 -input-list {list_file} \
                 -work-dir 'log_dir/layerwise_add_layer_log' \
                 -skip-initial-run \
                 -precision int8 \
                 -add-layers Add \
                 -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_add_layer_log/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
[================================================================================] 100.0% (65/65, skipped:55)
         Status         Layer Type              Shape Activations (Min,Max,Median) CosineSimilarity(%)                   Orig Outputs Info
O/P Name
317        skip               Clip  (1, 32, 112, 112)          (0.0, 2.962, 0.244)                   -                              -    -
320        skip               Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)                   -                              -    -
322        skip               Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)                   -                              -    -
325        skip               Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)                   -                              -    -
328        skip               Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)                   -                              -    -
330        skip               Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)                   -                              -    -
333        skip               Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)                   -                              -    -
336        skip               Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)                   -                              -    -
338        skip               Conv    (1, 24, 56, 56)      (-3.349, 3.994, -0.009)                   -                              -    -
339        part                Add    (1, 24, 56, 56)      (-4.153, 5.757, -0.012)             98.4206  {'473': {'CosineSimilarity...    -
342        skip               Clip   (1, 144, 56, 56)          (0.0, 1.796, 0.073)                   -                              -    -
345        skip               Clip   (1, 144, 28, 28)          (0.0, 2.466, 0.145)                   -                              -    -
347        skip               Conv    (1, 32, 28, 28)       (-2.48, 2.348, -0.021)                   -                              -    -
350        skip               Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)                   -                              -    -
353        skip               Clip   (1, 192, 28, 28)            (0.0, 1.581, 0.0)                   -                              -    -
355        skip               Conv    (1, 32, 28, 28)        (-2.185, 2.339, 0.01)                   -                              -    -
356        part                Add    (1, 32, 28, 28)      (-3.093, 3.128, -0.002)             99.9213  {'473': {'CosineSimilarity...    -
359        skip               Clip   (1, 192, 28, 28)           (0.0, 1.247, 0.09)                   -                              -    -
362        skip               Clip   (1, 192, 28, 28)            (0.0, 1.605, 0.0)                   -                              -    -
364        skip               Conv    (1, 32, 28, 28)       (-2.256, 1.801, 0.001)                   -                              -    -
365        part                Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)             99.9822  {'473': {'CosineSimilarity...    -
368        skip               Clip   (1, 192, 28, 28)           (0.0, 1.45, 0.067)                   -                              -    -
371        skip               Clip   (1, 192, 14, 14)          (0.0, 1.977, 0.204)                   -                              -    -
373        skip               Conv    (1, 64, 14, 14)      (-1.992, 2.155, -0.019)                   -                              -    -
376        skip               Clip   (1, 384, 14, 14)          (0.0, 0.875, 0.102)                   -                              -    -
379        skip               Clip   (1, 384, 14, 14)            (0.0, 1.127, 0.0)                   -                              -    -
381        skip               Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)                   -                              -    -
382        part                Add    (1, 64, 14, 14)       (-2.24, 2.105, -0.009)             99.9664  {'473': {'CosineSimilarity...    -
385        skip               Clip   (1, 384, 14, 14)          (0.0, 0.685, 0.059)                   -                              -    -
388        skip               Clip   (1, 384, 14, 14)            (0.0, 1.354, 0.0)                   -                              -    -
390        skip               Conv    (1, 64, 14, 14)       (-1.337, 1.224, 0.013)                   -                              -    -
391        part                Add    (1, 64, 14, 14)       (-2.812, 2.493, 0.001)             99.9732  {'473': {'CosineSimilarity...    -
394        skip               Clip   (1, 384, 14, 14)          (0.0, 0.687, 0.029)                   -                              -    -
397        skip               Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)                   -                              -    -
399        skip               Conv    (1, 64, 14, 14)       (-1.239, 1.442, 0.004)                   -                              -    -
400        part                Add    (1, 64, 14, 14)       (-2.687, 2.424, 0.003)             99.9871  {'473': {'CosineSimilarity...    -
403        skip               Clip   (1, 384, 14, 14)          (0.0, 0.904, 0.072)                   -                              -    -
406        skip               Clip   (1, 384, 14, 14)          (0.0, 1.945, 0.071)                   -                              -    -
408        skip               Conv    (1, 96, 14, 14)       (-2.516, 2.143, 0.005)                   -                              -    -
411        skip               Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)                   -                              -    -
414        skip               Clip   (1, 576, 14, 14)            (0.0, 2.021, 0.0)                   -                              -    -
416        skip               Conv    (1, 96, 14, 14)      (-1.555, 1.738, -0.002)                   -                              -    -
417        part                Add    (1, 96, 14, 14)       (-2.622, 2.259, 0.008)             99.9433  {'473': {'CosineSimilarity...    -
420        skip               Clip   (1, 576, 14, 14)            (0.0, 0.939, 0.0)                   -                              -    -
423        skip               Clip   (1, 576, 14, 14)            (0.0, 2.862, 0.0)                   -                              -    -
425        skip               Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)                   -                              -    -
426        part                Add    (1, 96, 14, 14)        (-4.119, 2.87, 0.009)             99.9633  {'473': {'CosineSimilarity...    -
429        skip               Clip   (1, 576, 14, 14)            (0.0, 1.563, 0.0)                   -                              -    -
432        skip               Clip     (1, 576, 7, 7)          (0.0, 2.461, 0.052)                   -                              -    -
434        skip               Conv     (1, 160, 7, 7)         (-1.268, 1.213, 0.0)                   -                              -    -
437        skip               Clip     (1, 960, 7, 7)          (0.0, 1.469, 0.036)                   -                              -    -
440        skip               Clip     (1, 960, 7, 7)             (0.0, 2.29, 0.0)                   -                              -    -
442        skip               Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)                   -                              -    -
443        part                Add     (1, 160, 7, 7)       (-1.563, 1.335, 0.018)             99.9249  {'473': {'CosineSimilarity...    -
446        skip               Clip     (1, 960, 7, 7)          (0.0, 1.054, 0.013)                   -                              -    -
449        skip               Clip     (1, 960, 7, 7)             (0.0, 1.57, 0.0)                   -                              -    -
451        skip               Conv     (1, 160, 7, 7)       (-1.429, 1.725, 0.001)                   -                              -    -
452        part                Add     (1, 160, 7, 7)       (-2.275, 2.112, 0.018)             99.9562  {'473': {'CosineSimilarity...    -
455        skip               Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)                   -                              -    -
458        skip               Clip     (1, 960, 7, 7)           (0.0, 1.35, 0.037)                   -                              -    -
460        skip               Conv     (1, 320, 7, 7)        (-1.671, 1.232, -0.0)                   -                              -    -
463        skip               Clip    (1, 1280, 7, 7)              (0.0, 6.0, 0.0)                   -                              -    -
464        skip  GlobalAveragePool    (1, 1280, 1, 1)           (0.0, 2.836, 0.42)                   -                              -    -
472        skip            Reshape          (1, 1280)           (0.0, 2.836, 0.42)                   -                              -    -
473        skip            (*)Gemm          (1, 1000)      (-7.962, 14.355, -0.18)                   -                              -    -
Results saved at log_dir/layerwise_add_layer_log/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise run result

In [76]:
csv_path = os.path.join(cwd , 'log_dir/layerwise_add_layer_log/layerwise.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Status,Layer Type,Shape,"Activations (Min,Max,Median)",CosineSimilarity(%),Orig Outputs,Info
0,317,skip,Clip,"(1, 32, 112, 112)","(0.0, 2.962, 0.244)",-,-,-
1,320,skip,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",-,-,-
2,322,skip,Conv,"(1, 16, 112, 112)","(-6.109, 5.047, -0.001)",-,-,-
3,325,skip,Clip,"(1, 96, 112, 112)","(0.0, 4.287, 0.154)",-,-,-
4,328,skip,Clip,"(1, 96, 56, 56)","(0.0, 3.188, 0.098)",-,-,-
5,330,skip,Conv,"(1, 24, 56, 56)","(-2.589, 3.013, -0.01)",-,-,-
6,333,skip,Clip,"(1, 144, 56, 56)","(0.0, 1.068, 0.13)",-,-,-
7,336,skip,Clip,"(1, 144, 56, 56)","(0.0, 2.844, 0.047)",-,-,-
8,338,skip,Conv,"(1, 24, 56, 56)","(-3.349, 3.994, -0.009)",-,-,-
9,339,part,Add,"(1, 24, 56, 56)","(-4.153, 5.757, -0.012)",98.4206,{'473': {'CosineSimilarity(%)': 97.9618}},-
10,342,skip,Clip,"(1, 144, 56, 56)","(0.0, 1.796, 0.073)",-,-,-
11,345,skip,Clip,"(1, 144, 28, 28)","(0.0, 2.466, 0.145)",-,-,-
12,347,skip,Conv,"(1, 32, 28, 28)","(-2.48, 2.348, -0.021)",-,-,-
13,350,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.007, 0.135)",-,-,-
14,353,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.581, 0.0)",-,-,-
15,355,skip,Conv,"(1, 32, 28, 28)","(-2.185, 2.339, 0.01)",-,-,-
16,356,part,Add,"(1, 32, 28, 28)","(-3.093, 3.128, -0.002)",99.9213,{'473': {'CosineSimilarity(%)': 99.5588}},-
17,359,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.247, 0.09)",-,-,-
18,362,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.605, 0.0)",-,-,-
19,364,skip,Conv,"(1, 32, 28, 28)","(-2.256, 1.801, 0.001)",-,-,-
20,365,part,Add,"(1, 32, 28, 28)","(-4.036, 3.924, -0.003)",99.9822,{'473': {'CosineSimilarity(%)': 99.7548}},-
21,368,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.45, 0.067)",-,-,-
22,371,skip,Clip,"(1, 192, 14, 14)","(0.0, 1.977, 0.204)",-,-,-
23,373,skip,Conv,"(1, 64, 14, 14)","(-1.992, 2.155, -0.019)",-,-,-
24,376,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.875, 0.102)",-,-,-
25,379,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.127, 0.0)",-,-,-
26,381,skip,Conv,"(1, 64, 14, 14)","(-1.842, 1.862, 0.011)",-,-,-
27,382,part,Add,"(1, 64, 14, 14)","(-2.24, 2.105, -0.009)",99.9664,{'473': {'CosineSimilarity(%)': 99.766}},-
28,385,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.685, 0.059)",-,-,-
29,388,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.354, 0.0)",-,-,-
30,390,skip,Conv,"(1, 64, 14, 14)","(-1.337, 1.224, 0.013)",-,-,-
31,391,part,Add,"(1, 64, 14, 14)","(-2.812, 2.493, 0.001)",99.9732,{'473': {'CosineSimilarity(%)': 99.7767}},-
32,394,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.687, 0.029)",-,-,-
33,397,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.319, 0.0)",-,-,-
34,399,skip,Conv,"(1, 64, 14, 14)","(-1.239, 1.442, 0.004)",-,-,-
35,400,part,Add,"(1, 64, 14, 14)","(-2.687, 2.424, 0.003)",99.9871,{'473': {'CosineSimilarity(%)': 99.7929}},-
36,403,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.904, 0.072)",-,-,-
37,406,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.945, 0.071)",-,-,-
38,408,skip,Conv,"(1, 96, 14, 14)","(-2.516, 2.143, 0.005)",-,-,-
39,411,skip,Clip,"(1, 576, 14, 14)","(0.0, 1.124, 0.01)",-,-,-
40,414,skip,Clip,"(1, 576, 14, 14)","(0.0, 2.021, 0.0)",-,-,-
41,416,skip,Conv,"(1, 96, 14, 14)","(-1.555, 1.738, -0.002)",-,-,-
42,417,part,Add,"(1, 96, 14, 14)","(-2.622, 2.259, 0.008)",99.9433,{'473': {'CosineSimilarity(%)': 99.7834}},-
43,420,skip,Clip,"(1, 576, 14, 14)","(0.0, 0.939, 0.0)",-,-,-
44,423,skip,Clip,"(1, 576, 14, 14)","(0.0, 2.862, 0.0)",-,-,-
45,425,skip,Conv,"(1, 96, 14, 14)","(-2.265, 2.364, 0.006)",-,-,-
46,426,part,Add,"(1, 96, 14, 14)","(-4.119, 2.87, 0.009)",99.9633,{'473': {'CosineSimilarity(%)': 99.8473}},-
47,429,skip,Clip,"(1, 576, 14, 14)","(0.0, 1.563, 0.0)",-,-,-
48,432,skip,Clip,"(1, 576, 7, 7)","(0.0, 2.461, 0.052)",-,-,-
49,434,skip,Conv,"(1, 160, 7, 7)","(-1.268, 1.213, 0.0)",-,-,-
50,437,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.469, 0.036)",-,-,-
51,440,skip,Clip,"(1, 960, 7, 7)","(0.0, 2.29, 0.0)",-,-,-
52,442,skip,Conv,"(1, 160, 7, 7)","(-1.003, 0.807, 0.015)",-,-,-
53,443,part,Add,"(1, 160, 7, 7)","(-1.563, 1.335, 0.018)",99.9249,{'473': {'CosineSimilarity(%)': 99.8258}},-
54,446,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.054, 0.013)",-,-,-
55,449,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.57, 0.0)",-,-,-
56,451,skip,Conv,"(1, 160, 7, 7)","(-1.429, 1.725, 0.001)",-,-,-
57,452,part,Add,"(1, 160, 7, 7)","(-2.275, 2.112, 0.018)",99.9562,{'473': {'CosineSimilarity(%)': 99.9182}},-
58,455,skip,Clip,"(1, 960, 7, 7)","(0.0, 0.882, 0.0)",-,-,-
59,458,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.35, 0.037)",-,-,-
60,460,skip,Conv,"(1, 320, 7, 7)","(-1.671, 1.232, -0.0)",-,-,-
61,463,skip,Clip,"(1, 1280, 7, 7)","(0.0, 6.0, 0.0)",-,-,-
62,464,skip,GlobalAveragePool,"(1, 1280, 1, 1)","(0.0, 2.836, 0.42)",-,-,-
63,472,skip,Reshape,"(1, 1280)","(0.0, 2.836, 0.42)",-,-,-
64,473,skip,(*)Gemm,"(1, 1000)","(-7.962, 14.355, -0.18)",-,-,-

## Executing layerwise run with skip layers
This run gives the layerwise snooping results on model by skipping specified op types (Conv,Clip,Add

*Note: User can use **-skip-layer-outputs** option to specify particular node to be skipped*

In [77]:
!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                 -reference onnxrt \
                 -snooping layerwise \
                 -comparator cos \
                 -tol-thres 0.01 \
                 -model {model_path} \
                 -input-list {list_file} \
                 -work-dir 'log_dir/layerwise_skip_layer_log' \
                 -skip-initial-run \
                 -precision int8 \
                 -skip-layers Conv,Clip,Add \
                 -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_skip_layer_log/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
[================================================================================] 100.0% (65/65, skipped:62)
         Status         Layer Type              Shape Activations (Min,Max,Median) CosineSimilarity(%)                   Orig Outputs Info
O/P Name
317        skip               Clip  (1, 32, 112, 112)          (0.0, 2.962, 0.244)                   -                              -    -
320        skip               Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)                   -                              -    -
322        skip               Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)                   -                              -    -
325        skip               Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)                   -                              -    -
328        skip               Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)                   -                              -    -
330        skip               Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)                   -                              -    -
333        skip               Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)                   -                              -    -
336        skip               Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)                   -                              -    -
338        skip               Conv    (1, 24, 56, 56)      (-3.349, 3.994, -0.009)                   -                              -    -
339        skip                Add    (1, 24, 56, 56)      (-4.153, 5.757, -0.012)                   -                              -    -
342        skip               Clip   (1, 144, 56, 56)          (0.0, 1.796, 0.073)                   -                              -    -
345        skip               Clip   (1, 144, 28, 28)          (0.0, 2.466, 0.145)                   -                              -    -
347        skip               Conv    (1, 32, 28, 28)       (-2.48, 2.348, -0.021)                   -                              -    -
350        skip               Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)                   -                              -    -
353        skip               Clip   (1, 192, 28, 28)            (0.0, 1.581, 0.0)                   -                              -    -
355        skip               Conv    (1, 32, 28, 28)        (-2.185, 2.339, 0.01)                   -                              -    -
356        skip                Add    (1, 32, 28, 28)      (-3.093, 3.128, -0.002)                   -                              -    -
359        skip               Clip   (1, 192, 28, 28)           (0.0, 1.247, 0.09)                   -                              -    -
362        skip               Clip   (1, 192, 28, 28)            (0.0, 1.605, 0.0)                   -                              -    -
364        skip               Conv    (1, 32, 28, 28)       (-2.256, 1.801, 0.001)                   -                              -    -
365        skip                Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)                   -                              -    -
368        skip               Clip   (1, 192, 28, 28)           (0.0, 1.45, 0.067)                   -                              -    -
371        skip               Clip   (1, 192, 14, 14)          (0.0, 1.977, 0.204)                   -                              -    -
373        skip               Conv    (1, 64, 14, 14)      (-1.992, 2.155, -0.019)                   -                              -    -
376        skip               Clip   (1, 384, 14, 14)          (0.0, 0.875, 0.102)                   -                              -    -
379        skip               Clip   (1, 384, 14, 14)            (0.0, 1.127, 0.0)                   -                              -    -
381        skip               Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)                   -                              -    -
382        skip                Add    (1, 64, 14, 14)       (-2.24, 2.105, -0.009)                   -                              -    -
385        skip               Clip   (1, 384, 14, 14)          (0.0, 0.685, 0.059)                   -                              -    -
388        skip               Clip   (1, 384, 14, 14)            (0.0, 1.354, 0.0)                   -                              -    -
390        skip               Conv    (1, 64, 14, 14)       (-1.337, 1.224, 0.013)                   -                              -    -
391        skip                Add    (1, 64, 14, 14)       (-2.812, 2.493, 0.001)                   -                              -    -
394        skip               Clip   (1, 384, 14, 14)          (0.0, 0.687, 0.029)                   -                              -    -
397        skip               Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)                   -                              -    -
399        skip               Conv    (1, 64, 14, 14)       (-1.239, 1.442, 0.004)                   -                              -    -
400        skip                Add    (1, 64, 14, 14)       (-2.687, 2.424, 0.003)                   -                              -    -
403        skip               Clip   (1, 384, 14, 14)          (0.0, 0.904, 0.072)                   -                              -    -
406        skip               Clip   (1, 384, 14, 14)          (0.0, 1.945, 0.071)                   -                              -    -
408        skip               Conv    (1, 96, 14, 14)       (-2.516, 2.143, 0.005)                   -                              -    -
411        skip               Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)                   -                              -    -
414        skip               Clip   (1, 576, 14, 14)            (0.0, 2.021, 0.0)                   -                              -    -
416        skip               Conv    (1, 96, 14, 14)      (-1.555, 1.738, -0.002)                   -                              -    -
417        skip                Add    (1, 96, 14, 14)       (-2.622, 2.259, 0.008)                   -                              -    -
420        skip               Clip   (1, 576, 14, 14)            (0.0, 0.939, 0.0)                   -                              -    -
423        skip               Clip   (1, 576, 14, 14)            (0.0, 2.862, 0.0)                   -                              -    -
425        skip               Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)                   -                              -    -
426        skip                Add    (1, 96, 14, 14)        (-4.119, 2.87, 0.009)                   -                              -    -
429        skip               Clip   (1, 576, 14, 14)            (0.0, 1.563, 0.0)                   -                              -    -
432        skip               Clip     (1, 576, 7, 7)          (0.0, 2.461, 0.052)                   -                              -    -
434        skip               Conv     (1, 160, 7, 7)         (-1.268, 1.213, 0.0)                   -                              -    -
437        skip               Clip     (1, 960, 7, 7)          (0.0, 1.469, 0.036)                   -                              -    -
440        skip               Clip     (1, 960, 7, 7)             (0.0, 2.29, 0.0)                   -                              -    -
442        skip               Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)                   -                              -    -
443        skip                Add     (1, 160, 7, 7)       (-1.563, 1.335, 0.018)                   -                              -    -
446        skip               Clip     (1, 960, 7, 7)          (0.0, 1.054, 0.013)                   -                              -    -
449        skip               Clip     (1, 960, 7, 7)             (0.0, 1.57, 0.0)                   -                              -    -
451        skip               Conv     (1, 160, 7, 7)       (-1.429, 1.725, 0.001)                   -                              -    -
452        skip                Add     (1, 160, 7, 7)       (-2.275, 2.112, 0.018)                   -                              -    -
455        skip               Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)                   -                              -    -
458        skip               Clip     (1, 960, 7, 7)           (0.0, 1.35, 0.037)                   -                              -    -
460        skip               Conv     (1, 320, 7, 7)        (-1.671, 1.232, -0.0)                   -                              -    -
463        skip               Clip    (1, 1280, 7, 7)              (0.0, 6.0, 0.0)                   -                              -    -
464        part  GlobalAveragePool    (1, 1280, 1, 1)           (0.0, 2.836, 0.42)             98.5525  {'473': {'CosineSimilarity...    -
472        part            Reshape          (1, 1280)           (0.0, 2.836, 0.42)               100.0  {'473': {'CosineSimilarity...    -
473                        (*)Gemm          (1, 1000)      (-7.962, 14.355, -0.18)             99.9945  {'473': {'CosineSimilarity...    -
Results saved at log_dir/layerwise_skip_layer_log/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise run result

In [78]:
csv_path = os.path.join(cwd , 'log_dir/layerwise_skip_layer_log/layerwise.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Status,Layer Type,Shape,"Activations (Min,Max,Median)",CosineSimilarity(%),Orig Outputs,Info
0,317,skip,Clip,"(1, 32, 112, 112)","(0.0, 2.962, 0.244)",-,-,-
1,320,skip,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",-,-,-
2,322,skip,Conv,"(1, 16, 112, 112)","(-6.109, 5.047, -0.001)",-,-,-
3,325,skip,Clip,"(1, 96, 112, 112)","(0.0, 4.287, 0.154)",-,-,-
4,328,skip,Clip,"(1, 96, 56, 56)","(0.0, 3.188, 0.098)",-,-,-
5,330,skip,Conv,"(1, 24, 56, 56)","(-2.589, 3.013, -0.01)",-,-,-
6,333,skip,Clip,"(1, 144, 56, 56)","(0.0, 1.068, 0.13)",-,-,-
7,336,skip,Clip,"(1, 144, 56, 56)","(0.0, 2.844, 0.047)",-,-,-
8,338,skip,Conv,"(1, 24, 56, 56)","(-3.349, 3.994, -0.009)",-,-,-
9,339,skip,Add,"(1, 24, 56, 56)","(-4.153, 5.757, -0.012)",-,-,-
10,342,skip,Clip,"(1, 144, 56, 56)","(0.0, 1.796, 0.073)",-,-,-
11,345,skip,Clip,"(1, 144, 28, 28)","(0.0, 2.466, 0.145)",-,-,-
12,347,skip,Conv,"(1, 32, 28, 28)","(-2.48, 2.348, -0.021)",-,-,-
13,350,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.007, 0.135)",-,-,-
14,353,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.581, 0.0)",-,-,-
15,355,skip,Conv,"(1, 32, 28, 28)","(-2.185, 2.339, 0.01)",-,-,-
16,356,skip,Add,"(1, 32, 28, 28)","(-3.093, 3.128, -0.002)",-,-,-
17,359,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.247, 0.09)",-,-,-
18,362,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.605, 0.0)",-,-,-
19,364,skip,Conv,"(1, 32, 28, 28)","(-2.256, 1.801, 0.001)",-,-,-
20,365,skip,Add,"(1, 32, 28, 28)","(-4.036, 3.924, -0.003)",-,-,-
21,368,skip,Clip,"(1, 192, 28, 28)","(0.0, 1.45, 0.067)",-,-,-
22,371,skip,Clip,"(1, 192, 14, 14)","(0.0, 1.977, 0.204)",-,-,-
23,373,skip,Conv,"(1, 64, 14, 14)","(-1.992, 2.155, -0.019)",-,-,-
24,376,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.875, 0.102)",-,-,-
25,379,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.127, 0.0)",-,-,-
26,381,skip,Conv,"(1, 64, 14, 14)","(-1.842, 1.862, 0.011)",-,-,-
27,382,skip,Add,"(1, 64, 14, 14)","(-2.24, 2.105, -0.009)",-,-,-
28,385,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.685, 0.059)",-,-,-
29,388,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.354, 0.0)",-,-,-
30,390,skip,Conv,"(1, 64, 14, 14)","(-1.337, 1.224, 0.013)",-,-,-
31,391,skip,Add,"(1, 64, 14, 14)","(-2.812, 2.493, 0.001)",-,-,-
32,394,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.687, 0.029)",-,-,-
33,397,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.319, 0.0)",-,-,-
34,399,skip,Conv,"(1, 64, 14, 14)","(-1.239, 1.442, 0.004)",-,-,-
35,400,skip,Add,"(1, 64, 14, 14)","(-2.687, 2.424, 0.003)",-,-,-
36,403,skip,Clip,"(1, 384, 14, 14)","(0.0, 0.904, 0.072)",-,-,-
37,406,skip,Clip,"(1, 384, 14, 14)","(0.0, 1.945, 0.071)",-,-,-
38,408,skip,Conv,"(1, 96, 14, 14)","(-2.516, 2.143, 0.005)",-,-,-
39,411,skip,Clip,"(1, 576, 14, 14)","(0.0, 1.124, 0.01)",-,-,-
40,414,skip,Clip,"(1, 576, 14, 14)","(0.0, 2.021, 0.0)",-,-,-
41,416,skip,Conv,"(1, 96, 14, 14)","(-1.555, 1.738, -0.002)",-,-,-
42,417,skip,Add,"(1, 96, 14, 14)","(-2.622, 2.259, 0.008)",-,-,-
43,420,skip,Clip,"(1, 576, 14, 14)","(0.0, 0.939, 0.0)",-,-,-
44,423,skip,Clip,"(1, 576, 14, 14)","(0.0, 2.862, 0.0)",-,-,-
45,425,skip,Conv,"(1, 96, 14, 14)","(-2.265, 2.364, 0.006)",-,-,-
46,426,skip,Add,"(1, 96, 14, 14)","(-4.119, 2.87, 0.009)",-,-,-
47,429,skip,Clip,"(1, 576, 14, 14)","(0.0, 1.563, 0.0)",-,-,-
48,432,skip,Clip,"(1, 576, 7, 7)","(0.0, 2.461, 0.052)",-,-,-
49,434,skip,Conv,"(1, 160, 7, 7)","(-1.268, 1.213, 0.0)",-,-,-
50,437,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.469, 0.036)",-,-,-
51,440,skip,Clip,"(1, 960, 7, 7)","(0.0, 2.29, 0.0)",-,-,-
52,442,skip,Conv,"(1, 160, 7, 7)","(-1.003, 0.807, 0.015)",-,-,-
53,443,skip,Add,"(1, 160, 7, 7)","(-1.563, 1.335, 0.018)",-,-,-
54,446,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.054, 0.013)",-,-,-
55,449,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.57, 0.0)",-,-,-
56,451,skip,Conv,"(1, 160, 7, 7)","(-1.429, 1.725, 0.001)",-,-,-
57,452,skip,Add,"(1, 160, 7, 7)","(-2.275, 2.112, 0.018)",-,-,-
58,455,skip,Clip,"(1, 960, 7, 7)","(0.0, 0.882, 0.0)",-,-,-
59,458,skip,Clip,"(1, 960, 7, 7)","(0.0, 1.35, 0.037)",-,-,-
60,460,skip,Conv,"(1, 320, 7, 7)","(-1.671, 1.232, -0.0)",-,-,-
61,463,skip,Clip,"(1, 1280, 7, 7)","(0.0, 6.0, 0.0)",-,-,-
62,464,part,GlobalAveragePool,"(1, 1280, 1, 1)","(0.0, 2.836, 0.42)",98.5525,{'473': {'CosineSimilarity(%)': 97.9618}},-
63,472,part,Reshape,"(1, 1280)","(0.0, 2.836, 0.42)",100.0,{'473': {'CosineSimilarity(%)': 99.9946}},-
64,473,NaN,(*)Gemm,"(1, 1000)","(-7.962, 14.355, -0.18)",99.9945,{'473': {'CosineSimilarity(%)': 99.9945}},-

### Executing Layerwise run on model with skip_layer_patterns option
This run performs layerwise run on all nodes of model by skipping node fusion patterns provided by user.


In this case, user needs to provide yaml file which contains the list of layer patterns to be skipped

eg : [['Conv','Relu'],['Conv','Batchnorm','Relu']]

In [60]:
!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                -reference onnxrt \
                -snooping layerwise \
                -comparator cos \
                -tol-thres 0.01 \
                -model {model_path} \
                -input-list {list_file} \
                -work-dir 'log_dir/layerwise_skiplayer_pattern_log_dir' \
                -skip-initial-run \
                -precision int8 \
                -skip-layer-patterns 'mobilenet/patterns.yaml' \
                -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/layerwise_skip_patterns_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
[================================================================================] 100.0% (65/65, skipped:0)
         Status         Layer Type              Shape Activations (Min,Max,Median)  CosineSimilarity(%)                   Orig Outputs Info
O/P Name
317        part               Clip  (1, 32, 112, 112)          (0.0, 2.962, 0.244)              99.9911  {'473': {'CosineSimilarity...    -
320        part               Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)              99.9290  {'473': {'CosineSimilarity...    -
322        part               Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)              99.9467  {'473': {'CosineSimilarity...    -
325        part               Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)              99.9758  {'473': {'CosineSimilarity...    -
328        part               Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)              99.9633  {'473': {'CosineSimilarity...    -
330        part               Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)              99.9802  {'473': {'CosineSimilarity...    -
333        part               Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)              99.9901  {'473': {'CosineSimilarity...    -
336        part               Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)              99.9798  {'473': {'CosineSimilarity...    -
338        part               Conv    (1, 24, 56, 56)      (-3.349, 3.994, -0.009)              99.9787  {'473': {'CosineSimilarity...    -
339        part                Add    (1, 24, 56, 56)      (-4.153, 5.757, -0.012)              99.9845  {'473': {'CosineSimilarity...    -
342        part               Clip   (1, 144, 56, 56)          (0.0, 1.796, 0.073)              99.9841  {'473': {'CosineSimilarity...    -
345        part               Clip   (1, 144, 28, 28)          (0.0, 2.466, 0.145)              99.9845  {'473': {'CosineSimilarity...    -
347        part               Conv    (1, 32, 28, 28)       (-2.48, 2.348, -0.021)              99.9876  {'473': {'CosineSimilarity...    -
350        part               Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)              99.9910  {'473': {'CosineSimilarity...    -
353        part               Clip   (1, 192, 28, 28)            (0.0, 1.581, 0.0)              99.9566  {'473': {'CosineSimilarity...    -
355        part               Conv    (1, 32, 28, 28)        (-2.185, 2.339, 0.01)              99.9841  {'473': {'CosineSimilarity...    -
356        part                Add    (1, 32, 28, 28)      (-3.093, 3.128, -0.002)              99.9922  {'473': {'CosineSimilarity...    -
359        part               Clip   (1, 192, 28, 28)           (0.0, 1.247, 0.09)              99.9856  {'473': {'CosineSimilarity...    -
362        part               Clip   (1, 192, 28, 28)            (0.0, 1.605, 0.0)              99.9773  {'473': {'CosineSimilarity...    -
364        part               Conv    (1, 32, 28, 28)       (-2.256, 1.801, 0.001)              99.9751  {'473': {'CosineSimilarity...    -
365        part                Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)              99.9915  {'473': {'CosineSimilarity...    -
368        part               Clip   (1, 192, 28, 28)           (0.0, 1.45, 0.067)              99.9863  {'473': {'CosineSimilarity...    -
371        part               Clip   (1, 192, 14, 14)          (0.0, 1.977, 0.204)              99.9947  {'473': {'CosineSimilarity...    -
373        part               Conv    (1, 64, 14, 14)      (-1.992, 2.155, -0.019)              99.9857  {'473': {'CosineSimilarity...    -
376        part               Clip   (1, 384, 14, 14)          (0.0, 0.875, 0.102)              99.9879  {'473': {'CosineSimilarity...    -
379        part               Clip   (1, 384, 14, 14)            (0.0, 1.127, 0.0)              99.9667  {'473': {'CosineSimilarity...    -
381        part               Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)              99.9859  {'473': {'CosineSimilarity...    -
382        part                Add    (1, 64, 14, 14)       (-2.24, 2.105, -0.009)              99.9932  {'473': {'CosineSimilarity...    -
385        part               Clip   (1, 384, 14, 14)          (0.0, 0.685, 0.059)              99.9838  {'473': {'CosineSimilarity...    -
388        part               Clip   (1, 384, 14, 14)            (0.0, 1.354, 0.0)              99.9401  {'473': {'CosineSimilarity...    -
390        part               Conv    (1, 64, 14, 14)       (-1.337, 1.224, 0.013)              99.9808  {'473': {'CosineSimilarity...    -
391        part                Add    (1, 64, 14, 14)       (-2.812, 2.493, 0.001)              99.9934  {'473': {'CosineSimilarity...    -
394        part               Clip   (1, 384, 14, 14)          (0.0, 0.687, 0.029)              99.9837  {'473': {'CosineSimilarity...    -
397        part               Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)              99.9831  {'473': {'CosineSimilarity...    -
399        part               Conv    (1, 64, 14, 14)       (-1.239, 1.442, 0.004)              99.9763  {'473': {'CosineSimilarity...    -
400        part                Add    (1, 64, 14, 14)       (-2.687, 2.424, 0.003)              99.9927  {'473': {'CosineSimilarity...    -
403        part               Clip   (1, 384, 14, 14)          (0.0, 0.904, 0.072)              99.9875  {'473': {'CosineSimilarity...    -
406        part               Clip   (1, 384, 14, 14)          (0.0, 1.945, 0.071)              99.9836  {'473': {'CosineSimilarity...    -
408        part               Conv    (1, 96, 14, 14)       (-2.516, 2.143, 0.005)              99.9829  {'473': {'CosineSimilarity...    -
411        part               Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)              99.9804  {'473': {'CosineSimilarity...    -
414        part               Clip   (1, 576, 14, 14)            (0.0, 2.021, 0.0)              99.9646  {'473': {'CosineSimilarity...    -
416        part               Conv    (1, 96, 14, 14)      (-1.555, 1.738, -0.002)              99.9808  {'473': {'CosineSimilarity...    -
417        part                Add    (1, 96, 14, 14)       (-2.622, 2.259, 0.008)              99.9902  {'473': {'CosineSimilarity...    -
420        part               Clip   (1, 576, 14, 14)            (0.0, 0.939, 0.0)              99.9758  {'473': {'CosineSimilarity...    -
423        part               Clip   (1, 576, 14, 14)            (0.0, 2.862, 0.0)              99.9745  {'473': {'CosineSimilarity...    -
425        part               Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)              99.9564  {'473': {'CosineSimilarity...    -
426        part                Add    (1, 96, 14, 14)        (-4.119, 2.87, 0.009)              99.9888  {'473': {'CosineSimilarity...    -
429        part               Clip   (1, 576, 14, 14)            (0.0, 1.563, 0.0)              99.9774  {'473': {'CosineSimilarity...    -
432        part               Clip     (1, 576, 7, 7)          (0.0, 2.461, 0.052)              99.9914  {'473': {'CosineSimilarity...    -
434        part               Conv     (1, 160, 7, 7)         (-1.268, 1.213, 0.0)              99.9719  {'473': {'CosineSimilarity...    -
437        part               Clip     (1, 960, 7, 7)          (0.0, 1.469, 0.036)              99.9755  {'473': {'CosineSimilarity...    -
440        part               Clip     (1, 960, 7, 7)             (0.0, 2.29, 0.0)              99.9531  {'473': {'CosineSimilarity...    -
442        part               Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)              99.9678  {'473': {'CosineSimilarity...    -
443        part                Add     (1, 160, 7, 7)       (-1.563, 1.335, 0.018)              99.9869  {'473': {'CosineSimilarity...    -
446        part               Clip     (1, 960, 7, 7)          (0.0, 1.054, 0.013)              99.9808  {'473': {'CosineSimilarity...    -
449        part               Clip     (1, 960, 7, 7)             (0.0, 1.57, 0.0)              99.9770  {'473': {'CosineSimilarity...    -
451        part               Conv     (1, 160, 7, 7)       (-1.429, 1.725, 0.001)              99.9686  {'473': {'CosineSimilarity...    -
452        part                Add     (1, 160, 7, 7)       (-2.275, 2.112, 0.018)              99.9881  {'473': {'CosineSimilarity...    -
455        part               Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)              99.9672  {'473': {'CosineSimilarity...    -
458        part               Clip     (1, 960, 7, 7)           (0.0, 1.35, 0.037)              99.9831  {'473': {'CosineSimilarity...    -
460        part               Conv     (1, 320, 7, 7)        (-1.671, 1.232, -0.0)              99.9508  {'473': {'CosineSimilarity...    -
463        part               Clip    (1, 1280, 7, 7)              (0.0, 6.0, 0.0)              99.9922  {'473': {'CosineSimilarity...    -
464        part  GlobalAveragePool    (1, 1280, 1, 1)           (0.0, 2.836, 0.42)              99.9987  {'473': {'CosineSimilarity...    -
472        part            Reshape          (1, 1280)           (0.0, 2.836, 0.42)             100.0000  {'473': {'CosineSimilarity...    -
473                        (*)Gemm          (1, 1000)      (-7.962, 14.355, -0.18)              99.9945  {'473': {'CosineSimilarity...    -
Results saved at log_dir/layerwise_skip_patterns_log_dir/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise run result

In [3]:
csv_path = os.path.join(cwd , 'sample_log_dir/log_dir/layerwise_skiplayer_pattern_log_dir/layerwise.csv')
df=pd.read_csv(csv_path)
df

FileNotFoundError: [Errno 2] No such file or directory: '/home/adarisi/Analyzer_demo/sample_log_dir/log_dir/layerwise_skiplayer_pattern_log_dir/layerwise.csv'

## Executing Layerwise run on model with custom operator

This run preforms layerwise run on model with custom operator (QNMS) .User needs to supply custom op lib files for onnxrt and aic
as shown below.

In [79]:

!{sys.executable}  /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                    -reference onnxrt \
                    -snooping layerwise \
                    -comparator avg \
                    -tol-thres 0.01 \
                    -start-from-layer-output 728 \
                    -model 'yolo_custom_op/yolov5s_640_640_with_abp_qnms.onnx' \
                    -input-list 'yolo_custom_op/list.txt' \
                    -work-dir 'log_dir/layerwise_cus_op_log_dir' \
                    -skip-initial-run \
                    -precision fp16 \
                    -disable-check-model \
                    -disable-graph-optimization \
                    -onnx-custom-op-lib 'yolo_custom_op/libCustomQnmsYoloOrt.so' \
                    -aic-compile-args="register-custom-op=yolo_custom_op/CustomQnmsConfig.yaml" \
                    -device-id {device_id}

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
INFO: Total no of nodes in the cleaned graph : 279
INFO: Node types and count in the cleaned graph:
       op_type  count
           Mul     72
          Conv     62
       Sigmoid     62
         Slice     23
        Concat     20
           Add     11
       Reshape      9
           Sub      4
       MaxPool      3
     Transpose      3
           Pow      3
        Resize      2
           Div      2
         Split      1
     Unsqueeze      1
CustomQnmsYolo      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Started Snooping...
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..3% (1/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..6% (2/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..9% (3/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..1% (4/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..4% (5/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator..7% (6/7, skipped:0)
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
Warning: Unsupported operator CustomQnmsYolo. No schema registered for this operator.
[================================================================================] 100.0% (7/7, skipped:0)
                Status         Layer Type             Shape Activations (Min,Max,Median)   Avg(%)                   Orig Outputs Info
O/P Name
733               part              Slice     (1, 25200, 1)  (-45.332, 633.376, 274.603)  99.9818  {'num_detections': {'Avg(%...    -
738               part              Slice     (1, 25200, 1)  (-36.539, 632.138, 297.882)  99.9821  {'num_detections': {'Avg(%...    -
743               part              Slice     (1, 25200, 1)     (7.12, 715.263, 366.562)  99.9816  {'num_detections': {'Avg(%...    -
748               part              Slice     (1, 25200, 1)    (8.154, 700.176, 339.181)  99.9818  {'num_detections': {'Avg(%...    -
749               part             Concat     (1, 25200, 4)  (-45.332, 715.263, 320.191)  99.9818  {'num_detections': {'Avg(%...    -
750               part          Unsqueeze  (1, 25200, 1, 4)  (-45.332, 715.263, 320.191)  99.9818  {'num_detections': {'Avg(%...    -
detection_boxes         (*)CustomQnmsYolo      (1, 2080, 4)        (-0.117, 666.81, 0.0)  96.2250  {'num_detections': {'Avg(%...    -
Results saved at log_dir/layerwise_cus_op_log_dir/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Layerwise run result

In [80]:
csv_path = os.path.join(cwd , 'log_dir/layerwise_cus_op_log_dir/layerwise.csv')
df=pd.read_csv(csv_path)
df = df.fillna('')
df

,O/P Name,Status,Layer Type,Shape,"Activations (Min,Max,Median)",Avg(%),Orig Outputs,Info
0,733,part,Slice,"(1, 25200, 1)","(-45.332, 633.376, 274.603)",99.9818,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
1,738,part,Slice,"(1, 25200, 1)","(-36.539, 632.138, 297.882)",99.9821,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
2,743,part,Slice,"(1, 25200, 1)","(7.12, 715.263, 366.562)",99.9816,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
3,748,part,Slice,"(1, 25200, 1)","(8.154, 700.176, 339.181)",99.9818,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
4,749,part,Concat,"(1, 25200, 4)","(-45.332, 715.263, 320.191)",99.9818,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
5,750,part,Unsqueeze,"(1, 25200, 1, 4)","(-45.332, 715.263, 320.191)",99.9818,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-
6,detection_boxes,,(*)CustomQnmsYolo,"(1, 2080, 4)","(-0.117, 666.81, 0.0)",96.2250,"{'num_detections': {'Avg(%)': 99.2126}, 'detec...",-

# Strategies
Strategy mode combines various snooping techniques and identifies sensitive nodes/sub-graphs. This is easier to use and faster to run. Using strategy on a model can be helpful when you have no idea on what the sensitive parts of the graph are. There are various strategy modes that can be used to get info on critical parts of the model.

## Binary search
The goal of this strategy is to identify the top few sensitive nodes in the model. In the beginning, we do the reference run and collect the golden tensors for the outputs. Then we do OneShot Snooping, starting at various nodes in the model beginning at the input. We traverse through the model in a binary search fashion to identify the node where we see the increase in accuracy match. This will help us to find the sensitive node which might be causing the drop in the accuracy match.

![flow](images/Binary_search.PNG)

With reference to the below diagram, we initially start with a whole model as search space for the sensitive node and depending on the accuracy match at various nodes, we narrow our search space where we see higher drop in the accuracy match. At any point of time start_layer and end_layer denotes the search space to find the sensitive node. start_match and end_match denotes final graph output accuracy match when we start the Oneshot run from start_layer and end_layer respectively.

User can also use num-sensitive-nodes param to identify more than one sensitive node. But it is recommended to use Layerwise snooping or Sequential search, if the user wants to find more than couple of sensitive nodes.

*Note:* This is useful to identify 1 or 2 most sensitive nodes. This strategy is very quick to run (<15 min for 1or 2 sensitive nodes) and gives us an quick idea on what the sensitive nodes. User can then explore further in that portion of the graph to identify the issue.

### Executing Binary search strategy

In [87]:
!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                    -model {model_path} \
                    -input-list {list_file} \
                    -work-dir 'log_dir/bs_log_dir' \
                    -reference onnxrt \
                    -precision int8 \
                    -strategy binary \
                    -num-sensitive-nodes 1

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/bs_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Compiling and executing original model...
         Layer Type      Shape Activations (min,max,median)   Avg(%) Info
O/P Name
473         (*)Gemm  (1, 1000)      (-7.962, 14.355, -0.18)  69.3158    -
Results saved at log_dir/bs_log_dir/oneshot.csv
INFO: Final outputs mismatch observed.
INFO: Running binary strategy on the model...
[================================================================================] 100.0% (Sensitive nodes: 1/1
INFO: Sensitive nodes are ['320'].
INFO:
         Layer Type              Shape Activations (Min,Max,Median)  mean match%                  Orig Outputs
O/P Name
320            Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)      69.9453  {'473': {'Avg(%)': 69.9453}}
322            Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)      81.8692  {'473': {'Avg(%)': 81.8692}}
Results saved at log_dir/bs_log_dir/binary_search.csv
INFO: qaic-acc-analyzer ended successfully

### Binary search result

In [88]:
csv_path = os.path.join(cwd , 'log_dir/bs_log_dir/binary_search.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Layer Type,Shape,"Activations (Min,Max,Median)",mean match%,Orig Outputs
0,320,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",69.9453,"{'473': OrderedDict([('Avg(%)', 69.9453)])}"
1,322,Conv,"(1, 16, 112, 112)","(-6.109, 5.047, -0.001)",81.8692,"{'473': OrderedDict([('Avg(%)', 81.8692)])}"

# Sequential Search
This strategy is used to identify a sensitive sub graph as opposed to finding sensitive nodes with binary search. In this strategy we do Oneshot snooping starting with nodes at various positions (10%, 20%.......90%) and observe the final output accuracy match. This will give us information on which sub-graph has the most decrease in the output accuracy match.

We then do a Layerwise snooping on that sub-graph which has most decrease in the output accuracy match, to identify one or more sensitive nodes in that sub-graph. User can use granularity param (0-100) to change the size of the sensitive sub-graph to be identified. It is recommended to use lower granularity(5-10) for bigger models and higher granularity for smaller models (10-20).

![flow](images/Sequential_search.PNG)

*Note:* This can be used if we suspect a particular portion of the sub-graph might be sensitive. After the sequential-search, we will have an overall idea on which portions of the graph might be sensitive and will also be able to identify the sensitive nodes in that particular sub-graph.  This takes longer than binary search but way lesser time than complete model layerwise snooping, since we only do layerwise on a sensitive sub-graph

### Executing Sequential search strategy

In [89]:
!{sys.executable} /opt/qti-aic/tools/qaic-pytools/qaic-acc-analyzer.py \
                    -model {model_path} \
                    -input-list {list_file} \
                    -work-dir 'log_dir/ss_log_dir' \
                    -reference onnxrt \
                    -precision int8 \
                    -strategy sequential \
                    -granularity 10 \
                    -silent

DEBUG: Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
DEBUG: Creating converter from 7 to 5
DEBUG: Creating converter from 5 to 7
WARNING: Caffe models not supported in this environment.
INFO: Caffe engine is unsupported in this environment.
INFO: QAIC Model Analyzer
/local/mnt/workspace/DVA/ml-tools/qaic-pytools-dist/env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:350: UserWarning: Deprecation warning. This ORT build has ['CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. The next release (ORT 1.10) will require explicitly setting the providers parameter (as opposed to the current behavior of providers getting set/registered by default based on the build flags) when instantiating InferenceSession.For example, onnxruntime.InferenceSession(..., providers=["CUDAExecutionProvider"], ...)
  warnings.warn("Deprecation warning. This ORT build has {} enabled. ".format(available_providers) +
INFO: Cleaned and Optimized model is saved at log_dir/ss_log_dir/cleanmodel.onnx
INFO: Total no of nodes in the cleaned graph : 100
INFO: Node types and count in the cleaned graph:
          op_type  count
             Conv     52
             Clip     35
              Add     10
GlobalAveragePool      1
          Reshape      1
             Gemm      1
INFO: Snooping all intermediate outputs of model
DEBUG: OnnxRT quantization params : None
INFO: Captured reference onnxrt session data
INFO: Captured onnx profile
INFO: Compiling and executing original model...
         Layer Type      Shape Activations (min,max,median)   Avg(%) Info
O/P Name
473         (*)Gemm  (1, 1000)      (-7.962, 14.355, -0.18)  69.3158    -
Results saved at log_dir/ss_log_dir/oneshot.csv
INFO: Final outputs mismatch observed.
INFO: Running sequential strategy on the model...
INFO: ===========================================================================] 100.0% (Oneshot nodes: 10/10)
          Node Index Layer Type              Shape Activations (Min,Max,Median)  mean match%                  Orig Outputs
O/P Name
320                1       Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)      69.9453  {'473': {'Avg(%)': 69.9453}}
336                7       Clip   (1, 144, 56, 56)          (0.0, 2.844, 0.047)      84.8165  {'473': {'Avg(%)': 84.8165}}
350               13       Clip   (1, 192, 28, 28)          (0.0, 1.007, 0.135)      89.4926  {'473': {'Avg(%)': 89.4926}}
365               20        Add    (1, 32, 28, 28)      (-4.036, 3.924, -0.003)      88.4463  {'473': {'Avg(%)': 88.4463}}
381               26       Conv    (1, 64, 14, 14)       (-1.842, 1.862, 0.011)      88.5143  {'473': {'Avg(%)': 88.5143}}
397               33       Clip   (1, 384, 14, 14)            (0.0, 1.319, 0.0)      89.8720   {'473': {'Avg(%)': 89.872}}
411               39       Clip   (1, 576, 14, 14)           (0.0, 1.124, 0.01)      91.2683  {'473': {'Avg(%)': 91.2683}}
425               45       Conv    (1, 96, 14, 14)       (-2.265, 2.364, 0.006)      91.3650   {'473': {'Avg(%)': 91.365}}
442               52       Conv     (1, 160, 7, 7)       (-1.003, 0.807, 0.015)      93.2132  {'473': {'Avg(%)': 93.2132}}
455               58       Clip     (1, 960, 7, 7)            (0.0, 0.882, 0.0)      95.6660   {'473': {'Avg(%)': 95.666}}
Results saved at log_dir/ss_log_dir/sequential_search.csv
INFO: The most sensitive subgraph is between 317(node output 320) and 333(node output 336)
INFO: Doing a layerwise run from start_layer 317 to end_layer 333
[================================================================================] 100.0% (6/6, skipped:0)
         Status Layer Type              Shape Activations (Min,Max,Median)   Avg(%)                  Orig Outputs Info
O/P Name
320        part       Clip  (1, 32, 112, 112)            (0.0, 6.0, 0.321)  95.4516    {'333': {'Avg(%)': 85.65}}    -
322        part       Conv  (1, 16, 112, 112)      (-6.109, 5.047, -0.001)  94.4547  {'333': {'Avg(%)': 96.2046}}    -
325        part       Clip  (1, 96, 112, 112)          (0.0, 4.287, 0.154)  97.2263  {'333': {'Avg(%)': 96.3141}}    -
328        part       Clip    (1, 96, 56, 56)          (0.0, 3.188, 0.098)  96.4831  {'333': {'Avg(%)': 96.6738}}    -
330        part       Conv    (1, 24, 56, 56)       (-2.589, 3.013, -0.01)  97.2736  {'333': {'Avg(%)': 98.4265}}    -
333                (*)Clip   (1, 144, 56, 56)           (0.0, 1.068, 0.13)  98.8066  {'333': {'Avg(%)': 98.8066}}    -
Results saved at log_dir/ss_log_dir/layerwise.csv
Compilation Failures at nodes : []
Extraction Failures at nodes : []
Execution Failures at nodes : []
Comparition Failures at nodes : []
INFO: qaic-acc-analyzer ended successfully

### Sequential Search result

In [90]:
csv_path = os.path.join(cwd , 'log_dir/ss_log_dir/sequential_search.csv')
df=pd.read_csv(csv_path)
df

,O/P Name,Node Index,Layer Type,Shape,"Activations (Min,Max,Median)",mean match%,Orig Outputs
0,320,1,Clip,"(1, 32, 112, 112)","(0.0, 6.0, 0.321)",69.9453,"{'473': OrderedDict([('Avg(%)', 69.9453)])}"
1,336,7,Clip,"(1, 144, 56, 56)","(0.0, 2.844, 0.047)",84.8165,"{'473': OrderedDict([('Avg(%)', 84.8165)])}"
2,350,13,Clip,"(1, 192, 28, 28)","(0.0, 1.007, 0.135)",89.4926,"{'473': OrderedDict([('Avg(%)', 89.4926)])}"
3,365,20,Add,"(1, 32, 28, 28)","(-4.036, 3.924, -0.003)",88.4463,"{'473': OrderedDict([('Avg(%)', 88.4463)])}"
4,381,26,Conv,"(1, 64, 14, 14)","(-1.842, 1.862, 0.011)",88.5143,"{'473': OrderedDict([('Avg(%)', 88.5143)])}"
5,397,33,Clip,"(1, 384, 14, 14)","(0.0, 1.319, 0.0)",89.8720,"{'473': OrderedDict([('Avg(%)', 89.872)])}"
6,411,39,Clip,"(1, 576, 14, 14)","(0.0, 1.124, 0.01)",91.2683,"{'473': OrderedDict([('Avg(%)', 91.2683)])}"
7,425,45,Conv,"(1, 96, 14, 14)","(-2.265, 2.364, 0.006)",91.3650,"{'473': OrderedDict([('Avg(%)', 91.365)])}"
8,442,52,Conv,"(1, 160, 7, 7)","(-1.003, 0.807, 0.015)",93.2132,"{'473': OrderedDict([('Avg(%)', 93.2132)])}"
9,455,58,Clip,"(1, 960, 7, 7)","(0.0, 0.882, 0.0)",95.6660,"{'473': OrderedDict([('Avg(%)', 95.666)])}"

# Limitations
- Oneshot run will fail for big models like bert due to memory constraints of device
- Tool requires a onnxrt custom op lib file for models with custom-op